### ISSUE TITLE
POCO ODBC output parameter function is not working on windows sqlserver odbc

### ISSUE THREAD

**Issue by leoincedo** [pocoproject/poco#1043]
/*TODO - currently fails with following error:

[Microsoft][ODBC SQL Server Driver][SQL Server]Invalid parameter 
2 (''):  Data type 0x23 is a deprecated large object, or LOB, but is marked as output parameter.  
Deprecated types are not supported as output parameters.  Use current large object types instead.
*/
i read this comment in  ODBCSQLServerTest.cpp 

i want to poco ODBC on sqlserver,
but not working and showing up error message 

so i try to change the something...
1. change the ODBC type
   WVARLONGCHAR -> WVARCHAR in Binder.cpp 
   VARLONGCHAR -> VARCHAR in Binder.cpp 
2. Binder::synchronize()
   add to the output sync code 
   ex)  wstring or UTF16String output parameter 

if (_wstrings.size())
    {
        WStringMap::iterator it = _wstrings.begin();
        WStringMap::iterator end = _wstrings.end();
        for (; it != end; ++it)
            it->second->assign(it->first, std::wcslen(it->first));
    }

TEST CODE:

```
   std::wstring inParam = L"한글";
   std::wstring outParam;

try{
    session() << "{call storedProcedure(?, ?)}", in(inParam), out(outParam), now;
}catch(StatementException& ex){
    std::cout << ex.toString();
}
```

string and wstring type is working done..

plz checking this ....

**Comment by orlinhristov** [comment]
Hi Guys,

Please excuse me if this is not the right place to post my question, but I would like to ask if there is any chance to get this issue fixed. We've started a few new projects in our company and I convinced my colleagues to use Poco library. No doubt this is one of the best C++ libraries, suitable for professional projects . The problem is that we access our databases through an interface, built from stored procedures. Many of those have output parameters of type (n)varchar and we hit this error soon after we started our implementation. 

I also would like to ask if you have any suggestions of how to workaround it, if you are not planning to fix this issue at all.

Regards,
Orlin Hristov.

**Comment by aleks-f** [comment]
sorry for long wait
