### ISSUE TITLE
Poco JSON stringify error on Poco::JSON::Object

### ISSUE THREAD

**Issue by idekel** [pocoproject/poco#1054]
Hello,

I am having an Bad cast exception when try to assign enum constant and later call stringify. If I replace the enum constant with int or cast to int It works. Below I will paste some code so you can run it and see the error. I am using Poco 1.6.1 with g++ 4.8.5 on openSUSE Leap.

#include <iostream>

#include <Poco/JSON/Object.h>

using namespace std;

using Poco::JSON::Object;

class Test
{
public:

    enum {
        A = 0,
        B = 1,
        C = 2
    };

    Test() {}
};

int main()
{

    Object obj;
    obj.set("A", Test::A); //obj.set("A", 0); works
    obj.set("B", Test::B); //obj.set("B", 1); works
    obj.set("C", Test::C); //obj.set("C", 2); works

    obj.stringify(cout);

    return 0;
}

**Comment by aleks-f** [comment]
First, as you're trying to do it, there's no way it can be detected at compile time what the type of the value inside anonymous enum is. If you gave it a name, it could be detected through C++11 std::underlying type template, but still you're on your own there in specializing [VarHolder](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Dynamic/VarHolder.h) for your enum, because we can't specialize Dynamic::Var for any end-user enum.

Considering above, I suggest to simplify your life, cast to int and move on ...

**Comment by idekel** [comment]
Got it. I didn't know how it worked. Thanks for your so quick response.

**Comment by aleks-f** [comment]
no problem :)
