### ISSUE TITLE
CMake: use embedded openssl by default

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#1093]
Hi

The CMake FindOpenSSL.cmake is looking for default location as C:\OpenSSL-Win32 & C:\OpenSSL-Win64 and if found, use those locations. This precludes the usage of the internal openssl libs which are now packaged with the poco repo.

Thus the CMake  build should use by default the embedded openssl libs/includes except if a flag like ENABLE_EXTERN_OPENSSL=ON specifies to use the standard FindOpenSSL.cmake

**Comment by bachp** [comment]
I think there are more possibilies:

1. Use external OpenSSL
2. Use bundled OpenSSL
3. Don't use OpenSSL --> Disable functionality depending on OpenSSL

These should be reflected by the options.

**Comment by aleks-f** [comment]
If I understand it right, CMake generates it's  own VS projects, so there would be no conflict with progen-generated ones (which use bundled SSL by default) from that standpoint. I would, however, follow the same logic we have in a CMake-less build, i.e. use bundled by default, unless user specifies otherwise. 

Note that, for any unbundled SSL build on windows, [POCO_EXTERNAL_OPENSSL](https://github.com/pocoproject/poco/blob/develop/Crypto/include/Poco/Crypto/Crypto.h#L106) must be defined, otherwise bundled will be linked automatically.

This only applies for Windows, on other platforms there is no bundled SSL. The rationale for bundled openssl was that Crypto and NetSSL projects always had to be edited in order to build, which is quite annoying - we wan't to build out-of-the-box whenever reasonably possible.

**Comment by zosrothko** [comment]
An additional issue about openssl on Windows: When building poco with cmake in a  x64 environement, FindOpenSSL.cmake is chosing the Win32 directory when there is no C:\OpenSSL-Win64 directory

`-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Poco package version: 1.7.0
-- Found message compiler: C:/Program Files (x86)/Windows Kits/8.1/bin/x86/mc.exe
-- Building dynamic libraries
-- Building with unittests & samples
-- Build with using internal copy of sqlite, libz, pcre, expat, ...
-- ############ FIXME: NetSSLWin add_subdirectory(testsuite)
-- ############ FIXME: NetSSLWin add_subdirectory(samples)
-- Found OpenSSL: optimized;C:/OpenSSL-Win32/lib/VC/ssleay32MD.lib;debug;C:/OpenSSL-Win32/lib/VC/ssleay32MDd.lib;optimiz
ed;C:/OpenSSL-Win32/lib/VC/libeay32MD.lib;debug;C:/OpenSSL-Win32/lib/VC/libeay32MDd.lib (found version "1.0.1i")`

**Comment by aleks-f** [comment]
@zosrothko  can you adjust cmake to the three options as specified above by @bachp 

FWIW, I would default to bundled OpenSSL, like the pre-generated VS projects do - it's a safest bet because we know with 100% certainty where the libs are and what their name is

Note that the pre-built openssl scripts and binaries are now a [submodule](https://github.com/pocoproject/openssl) (only in 1.8.0 and in c++11 branches for now) - @zosrothko the directory layout under openssl/ has slightly changed - theres [VS_${vs_version}](https://github.com/pocoproject/openssl/tree/master/VS_120) subdir now, curently only VS_120, but just in case we ever have to build different binaries for different VS versions

**Comment by aleks-f** [comment]
update:

starting with 1.8.0 and 2.0.0, the plan is to release openssl windows build scripts only (*not* openssl binaries) with poco releases. 

aside for being relatively time consuming, windows openssl build also depends on fetching perl, nasm etc, so it is not wise to couple that with poco build. I will document how to build openssl using our build script, so users will be able to utilize that if they wish - building one's own ssl will be an optional step which will enable user to build Poco::Crypto and NetSSL transparently - without worrying where openssl is installed.

**Comment by aleks-f** [comment]
OpenSSL documentation [updated](https://github.com/pocoproject/poco/blob/develop/doc/00200-GettingStarted.page#L122) for all Windows/OpenSSL scenarios except CMake.

**Comment by aleks-f** [comment]
added in [develop](https://github.com/pocoproject/poco/commit/8da67bee2667949c276812378d0e5f00a8ea4f4c). Unless [DISABLE_INTERNAL_OPENSSL](https://github.com/pocoproject/poco/commit/8da67bee2667949c276812378d0e5f00a8ea4f4c#diff-af3b638bc2a3e6c650974192a53c7291R9) is specified, cmake will [look for %POCO_BASE%\VS_120 directory](https://github.com/pocoproject/poco/commit/8da67bee2667949c276812378d0e5f00a8ea4f4c#diff-af3b638bc2a3e6c650974192a53c7291R95). If the directory is found, OpenSSL headers/libraries are taken from there. Otherwise, cmake will try to find the system-installed OpenSSL.

@zosrothko can you update AppVeyor to use cmake build for at least one build? it looks to me it is not using cmake currently.

**Comment by zosrothko** [comment]
@aleks-f Thst's true. CMake has been removed because it is already run on Travis and the overall time for an AppVeyor CI time is 6 hours. Adding CMake will push this timing to 8 hours. As per your request,  I readd it for some time.

**Comment by aleks-f** [comment]
@zosrothko yes, appveyor timing is atrocious. can you just modify some of the current msbuild builds, to use cmake instead? and perhaps, have one cmake use internal openssl and the other system-installed (just give CMake `DISABLE_INTERNAL_OPENSSL=ON`)

**Comment by zosrothko** [comment]
The current MSBuild project are the minimum a CI should do for VisualStudio
only release/shared is build with VS2015 Win32/x64
only release/shared is build with VS2017 Win32/x64
So we cannot reduce more the timelapse for VisualStudio. The other build are for Cygwin Win32/x64 release/shared also.
So CMake will be added as
CMake/VS2015
CMake/VS2017 with DISABLE_INTERNAL_OPENSSL=ON

**Comment by zosrothko** [comment]
Verified
