### ISSUE TITLE
Automatic static initialization/registration (Data connectors)

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1163]
Automatic static initialization/registration of Data connectors has given me major trouble.
For example, when loading MySQL Connector from a shared library (as with OSP), it deadlocks in mysql_library_init()). I'm inclined to remove automatic registration from the DB connectors as it seems to cause more troubles than it's worth.

@aleks-f?

**Comment by aleks-f** [comment]
it was a nice try to simplify things. Sounds more like mysql bug than ours. I don't have a horse in that race nor do I know much about mysql - . @intensifi is Data maintainer so maybe he has a solution/opinion

**Comment by aleks-f** [comment]
Also, keep in mind that removing it will break runtime behavior of the code depending on it. Maybe there is a workaround for mysql?

**Comment by obiltschnig** [comment]
No, it's a classic static initialization order issue. mysql_library_init() will create a pthread, then join it at one point. Which is where it hangs.

**Comment by obiltschnig** [comment]
Interestingly it works on OS X. But hangs on the production machine, which is Linux.

**Comment by obiltschnig** [comment]
Don't have the time to look into this. For 1.7.0, I'll remove auto init from Data/MySQL. IMO this whole auto init thing has too many cases where the magic does not work anyway. At least on non-Windows platforms.

**Comment by aleks-f** [comment]
possibly: 

> mysql_library_init() is not thread-safe in a multi-threaded environment, and thus neither is mysql_init(), which calls mysql_library_init(). You must either call mysql_library_init() prior to spawning any threads, or else use a mutex to protect the call

http://dev.mysql.com/doc/refman/5.7/en/mysql-library-init.html

**Comment by obiltschnig** [comment]
No, it's not a multithreading issue. It's a static initialization order issue, calling mysql_library_init() before pthread static initialization is done. Solution would be to delay calling mysql_library_init() at a later point, e.g., before the first session is created. Don't have time to do that for 1.7, though.

**Comment by micheleselea** [comment]
in my previews question (#997) the problem was not of deadlock but was a long wait. I resolved calling the function Poco::Data::MySQL::Connector::registerConnector(); and unregister in the main thread, and not in thread created inside the main thread. This way the long wait is gone, but I do not know if on linux that kind of long wait perform as a deadlock

**Comment by aleks-f** [comment]
there is a simple solution to this problem - make the registrator a static variable in a function (eg. in Connector::createSession). That way its creation point can be controlled. But I won't do any work unless there is a consensus on it. /cc @obiltschnig @intensifi

**Comment by obiltschnig** [comment]
You just have to keep in mind that initialization of local statics is not thread-safe in earlier (pre-C++11) Visual C++ versions (at least up to and including 2008, which we still support in 1.7)

**Comment by aleks-f** [comment]
the mysql_init call should be protected by mutex in any case because it is not thread safe. again, it does not matter to me one way or the other - we make it right and keep it or remove it. the main motivation behind it was to shield users from consequences of forgetting to register manually (or doing it multiple times, from multiple threads, which can cause problems in this case) - one line is not a problem if you know you have to write it and don't by accident write it multiple times in places you shouldn't

**Comment by aleks-f** [comment]
[fixed](https://github.com/pocoproject/poco/commit/8aecf8a9b0ff94a3a35fdd14f276e3894a90969e)
