### ISSUE TITLE
ConsoleChannel could try harder to cause just one hopefully atomic write per log()

### ISSUE THREAD

**Issue by tml1024** [pocoproject/poco#1166]
If you have multiple processes each doing logging to the same file, the outputs can get mixed up even if they all use (only) the Poco Logger API to a ConsoleChannel to output. A simple fix seems to be to change the:

_str << msg.getText() << std::endl;

in ConsoleChannel::log(const Message& msg) to: 

_str << msg.getText() + "\n";
_str.flush();

For ColorConsoleChannel it is a bit more complex, but the same idea should work.

**Comment by phirg** [comment]
If this works (avoids mix up), I would be interested too...

**Comment by obiltschnig** [comment]
This is not as easy as it sounds. The proposed solution with flush() won't work, as std:endl already is equivalent to writing '\n', followed by flushing the stream.
A single global mutex would work, but this will cause unnecessary locking if multiple processes write to different console windows (which is the more common scenario), so I don't like it either. Maybe the global lock could be made optional, controlled via a configuration propery. But then, the global lock won't save you if someone else writes to the console not using the ConsoleChannel...

**Comment by tml1024** [comment]
I know it is equivalent, that is why I have the flush() there. (But actually in my testing the flush() is not even necessary, at least not on Linux with GNU libstdc++.)

But note that the existing code is writing the '\n' separately (as part of the endl) while my suggested change makes sure the '\n' is part of the one string being output. *That* is the point.

I have a (simple) test program that demonstrates the issue without using Poco even:

```
#include <cstdlib>
#include <iostream>
#include <string>

int main(int, char **argv)
{
  static bool useEndl = std::getenv("USE_ENDL");

  for (int i = 0; i < 10000; i++) {
    if (useEndl)
      std::clog << std::string(argv[1]) << std::endl;
    else
      std::clog << std::string(argv[1]) + "\n";
  }

  return 0;
}
```

(I called it "x2.cpp" so the executable is "x2" below.)

Run on Linux, first as:

`((./x2 AAAAAAAAAAAAAAAAAAAAAAAAAA &); (./x2 BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB &)) >x2.appended-newline.out 2>&1`

then as:

`(export USE_ENDL=1; (./x2 AAAAAAAAAAAAAAAAAAAAAAAAAA &); (./x2 BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB &)) >x2.endl-instead-of-newline.out 2>&1`

You will notice that in the first case, all the output lines are cleanly either just As or just Bs, as intended. In the second case, however, there will be a significant number of lines that have either As followed by Bs and then an empty line, or Bs followed by As and an empty line. That is what I see with Poco, too: log() lines from separate processes being joined, with empty lines following.

Of course, that it works this way is because of some implementation dependent details related to buffering and buffer size of std::clog in libstdc++ on Linux. But anyway, I think that for "reasonable" length lines passed to log(), the change would be a clear improvement when you have multiple processes writing their log to the same output file. On Linux, that is. On other platforms, it won't make anything worse: On OS X, with libc++, you get intermixed As and Bs on the same lines (AAAABBBBAABB etc), regardless whether endl is used or not. There one would really need an inter-process mutex if one has several processes logging to the same output file.

So yeah, this is not a change that improves things cross-platform; it just (more or less by accident) helps on one platform (even if an important one), so I understand if you are reluctant to put it in.

**Comment by tml1024** [comment]
Wonder if there is any point in keeping this request alive? Should I just close it? Has the issue perhaps been handled already in current sources?

**Comment by aleks-f** [comment]
There's been no fix and there are no immediate plans to provide one. 

I think your implementation-specific "trick" works (perhaps by accident) because you locally "accumulate" the whole string, including '\n', before actually writing it.

But, it's not completely clear to me what you are trying to achieve - multiple processes writing to the same log file on disk, or one process writing to other process' stdout?

**Comment by obiltschnig** [comment]
If something could work, then an atomic write operation directly using the file descriptor (https://stackoverflow.com/questions/1154446/is-file-append-atomic-in-unix). This would involve creating a new LogFile_POSIX implementation. Same for ConsoleChannel.

Then Windows LogFile implementation already uses a file handle instead of file stream, but even here there are multiple WriteFile() calls.

Interestingly, WindowsConsoleChannel uses a single WriteFile() call and thus should be atomic in most cases (https://stackoverflow.com/questions/1154446/is-file-append-atomic-in-unix).

Let's leave this open as a feature request. No time to do it now, but pull request would be welcome.
