### ISSUE TITLE
Incorrect behaviour when command line arguments containing whitespace are passed to Process::launch() on Windows platforms

### ISSUE THREAD

**Issue by tonyabbott** [pocoproject/poco#1222]
Passing command line arguments containing whitespace to Process::launch() results in inconsistent behaviour between Windows and Unix platforms. On Unix platforms the arguments are passed to spawn() as individual arguments so there is no problem. On Windows platforms the arguments are concatenated into a single command line string using a space character as separator. This results in arguments (such as paths) containing whitespace being incorrectly interpreted as multiple arguments by the child process.

The fix is to properly quote the arguments on Windows. See https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/ for an explanation and sample code that correctly handles the more complex cases.

The problem is that this will change existing behaviour on Windows platforms which will cause problems where the calling code already adds quotes. One possible solution to this is to assume that any argument that starts and ends with quotes is already quoted and just append it to the command line as is.

**Comment by obiltschnig** [comment]
Could you implement the suggested correct solution (with an additional check if an argument is already quoted, then take as is) and provide a pull request?

**Comment by micheleselea** [comment]
Unfortunately I think is not the correct solution to escape always command line, at least not for all commands.
For example if you use
tasklist /FO CSV /NH
the command /FO CSV should not be between quote like
tasklist "/FO CSV" /NH
it's not such a problem because simply I can push 2 different arguments in args vector for Poco::Process::launch but obviously that break the compatibility with previous version. I found that the behavior changed brake me some call, so when you update double check where you use Poco::Process::launch

**Comment by obiltschnig** [comment]
AFAIC the fix is ok. Having two command-line args in the same args vector item will no longer work, of course, but such code has been broken anyway.
