### ISSUE TITLE
PCRE version

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1283]
Hi all, I have a question about PCRE version used in regular expression in Poco. I found that in Poco lib we use 8.35 (2014-04-04): current one on http://www.pcre.org/ is 10.21
I never find an "upgrade", like we have with SQLite for example, during Poco upgrade: do you know if we should use 8.35 for some particolar reason?
It's just a question because Poco::RegularExpression works good, perhaps in newer version of pcre something about "speed" was done

**Comment by obiltschnig** [comment]
Upgrading PCRE usually requires a certain amount of work (due to changed filenames or additional files, etc), that's why it's only done if absolutely necessary (or someone invests the time to do it). Also, there are some dependencies on implementation details of PCRE, which may break with newer versions (Poco::Unicode).
In contrast, an SQLite upgrade consists of replacing two files and running the tests, which is less than 5 minutes of work.
If you want to do the work to upgrade to latest PCRE, you're welcome.

**Comment by micheleselea** [comment]
Ok thank you for reply, I'll check if I found the to have some dig in RegularExpression code. I don't know if I can have a comprehensive test case but I'll try
