### ISSUE TITLE
how to compile source for android using CMake

### ISSUE THREAD

**Issue by ntimesc** [pocoproject/poco#1289]
i am trying to compile poco for android using CMake , i am using CMake 3.5.2 and Android CMake 

[https://github.com/taka-no-me/android-cmake](url)

``````
C:\Program Files (x86)\CMake\bin>cmake -DCMAKE_TOOLCHAIN_FILE="E:\ndk\android-cm
ake-master\android.toolchain.cmake" -DANDROID_NDK="D:\android-ndk-r10e" -DCMAKE_
BUILD_TYPE=Release -DANDROID_ABI="armeabi" "E:\ndk\poco-1.7.3" && cmake --build

```.

i am getting following error 

> CMake Error at CMakeLists.txt:11 (project):
>   CMAKE_SYSTEM_NAME is 'Android' but 'NVIDIA Nsight Tegra Visual Studio
>   Edition' is not installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/Program Files (x86)/CMake/bin/CMakeFiles/CMakeOutput.log".


can anyone please suggest a proper roadmap to compile it for android , i hunt over a net a lot but couldnt find anything
``````

**Comment by aviadmini** [comment]
I used **make** + [standalone toolchains](https://developer.android.com/ndk/guides/standalone_toolchain.html) + slightly modified build config:

```

...

ifeq ($(ANDROID_ABI),armeabi)
TOOL      = arm-linux-androideabi
ARCHFLAGS = -mthumb
else
ifeq ($(ANDROID_ABI),armeabi-v7a)
TOOL      = arm-linux-androideabi
ARCHFLAGS = -march=armv7-a -mfloat-abi=softfp
LINKFLAGS = -Wl,--fix-cortex-a8
else
ifeq ($(ANDROID_ABI),x86)
TOOL      = i686-linux-android
ARCHFLAGS = -march=i686 -msse3 -mstackrealign -mfpmath=sse
else
ifeq ($(ANDROID_ABI),x86_64)
TOOL      = x86_64-linux-android
ARCHFLAGS = -msse3 -mstackrealign -mfpmath=sse
else
ifeq ($(ANDROID_ABI),arm64-v8a)
TOOL      = aarch64-linux-android
ARCHFLAGS = -mabi=lp64 -march=armv8-a
else
$(error Invalid ABI specified in ANDROID_ABI)
endif
endif
endif
endif
endif

...

```

Then I used [gradle-experimental](http://tools.android.com/tech-docs/new-build-system/gradle-experimental) plugin to link prebuilt libraries.
There was an issue with Poco.Net which depends on Poco.Foundation and I couldn't find a good way to set a dependency for a prebuilt library so I created a native module (apply plugin: 'com.android.model.native') which compiled Poco.Net with prebuilt Poco.Foundation dependency. It's slightly complicated because you need correct c/cpp flags but you can look them up in Poco docs.

Actually it might be a good idea to update documentation/Android config file to correspond latest changes.

**Comment by ntimesc** [comment]
can you please share your build files please or a compile project so that i can study it. Am doing this for the first time so expecting some definite roadmap if you could provide

**Comment by aviadmini** [comment]
In my previous post I wrote sufficient details on how to achieve this. I'm not planning to write a tutorial for beginners
