### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by steji113** [pocoproject/poco#1341]
Is there any possibility you guys can make a Nuget package and maintain it as new releases are made? This would be extremely helpful to those leveraging Nuget's C++ support.

Thank you!

**Comment by zosrothko** [comment]
Your contribution for building such Nuget package for poco is wellcome in this repo https://github.com/pocoproject/distro under the Windows directory.

**Comment by steji113** [comment]
@zosrothko Do you have an existing .autopkg script for the Nuget that is currently published or do you need a new one?

**Comment by zosrothko** [comment]
No development has been done yat for packaging Poco as a Nutget package. Thus everything is to build from scratch. There is already a WiX script for packaging Poco as a msi.

**Comment by steji113** [comment]
@zosrothko The NuGet .autopkg file needs to be able to reference the includes and libs via a relative path, so I think it might have to be included in the main repository.

Also, I was planning on starting out with static MT configuration first as that seems to be pretty common on NuGet. Then I would make a separate package for each library, e.g. poco-foundation, poco-crypto, etc...

Does this sound alright?

**Comment by zosrothko** [comment]
Yeap... but you could build the .autopkg under the  https://github.com/pocoproject/distro repo. Look at the Windows/build.cmd. Building the msi pakage needs before to build poco libs. Thus steps are
1/ git clone https://github.com/pocoproject/poco.git poco
2/ cd poco
3/ buildwin 140 build ....
4/ cd ..
5/ git clone https://github.com/pocoproject/distro.git
6/ cd distro/Windows/Nuget
7/.....

Then .autopkg can refers libs and includes using a relative path.

Otherwise, there is a another solution -- which IMO  seems cleaner/easier/faster -- is to instal the Poco msi package downloaded from  https://github.com/pocoproject/distro/releases and uses the includes/libs path installed at the standard windows programs location.

**Comment by steji113** [comment]
Ah yes the MSI installer might be the easiest! Do you plan to make one available for 1.7.4? Otherwise I can base it off of 1.7.3 for now. Since it looks like there is only a VS 2013 installer for now I will include that to start off with.

**Comment by zosrothko** [comment]
Yes there should be a 1.7.4 release... and may be  you would be interested in building the Poco-1.7.4 msi. That would be a way to share knowledge about packaging Poco since up to now, I am the only one in the distro area. I would let you know all needed details for building Poco msi.

**Comment by steji113** [comment]
I imagine the NuGet files should be the same (mostly) for the two versions other than the version number. Let me give the 1.7.3 a shot to see if it all works first.

**Comment by zosrothko** [comment]
No problem...

**Comment by zosrothko** [comment]
We are using Slack for instant chat on Poco... You can join the pocoproject at slack

**Comment by steji113** [comment]
I seem to be having some trouble with how things are installed with the MSI installers.

Ideally we would have one output directory as a result of a build that would be setup like so:

* output\
  * include\
    * Crypto\
    * Foundation\
    * ...
  * lib\
    * vs2013\
      * Win32\
      * x64\
    * vs2015\
      * Win32\
      * x64\

Ultimately, all of the includes should be completely self contained within their own project's directory. Also, the lib outputs should be differentiated based on compiler platform and target platform. I am also suggesting that we try to tackle MT and MTD static libs at first, as it makes things easier with NuGet.

Would a change like this be possible? Also, one thing I am not currently aware of, is what projects have dependencies on other Poco projects. For example, does Net rely on Foundation?

Thanks!

**Comment by zosrothko** [comment]
here some thougths on the MSI packaging (not on Nuget packaging)
1/ the include directory should be named 'inc' and not 'include' to follow the library directory named 'lib' and the binaries directory named 'bin'

2/ There is no need to have a Win32 and x64 subdirectory since the high level qualifier in Windows splits already the stuff. Win32 objects should go into ````C:\Program Files (x86)```` and x64 objects should go into ````C:\Program Files````

3/ Poco cannot be build in a single Poco source directory for both VS2013 and V2015. Either VS2013(Win32,x64) can be build, either VS2015(Win32,x64) can be build. Not both at the same time. So I would suggest to not split the lib subdirectory with VS2013/VS2015, but split  at a higher level as for example 
````C:\Program Files (x86)\Poco\1.7.4\vs120 and
C:\Program Files (x86)\Poco\1.7.4\vs140````

4/To get the inter module dependencies, look at the Makefile, the <module>-libexec provides  what you are looking for

5/ Please connect to Slack. It would avoid to bore poco users with detailled packaging discussion.
