### ISSUE TITLE
ApacheConnector.cpp use old apache old api interface

### ISSUE THREAD

**Issue by flachesis** [pocoproject/poco#14]
(apache 2.4)
ap_log_error(...) has change api interface,
and remote_ip and remote_addr,
change to client_ip and client_addr.

**Comment by yegorich** [comment]
Just heads up in the case that ApacheConnector is still going to be maintained. During my CMake related tests I've encountered following compilation error (Apache 2 version: apache2-dev 2.4.25-3+deb9u3, poco version: current git/develop branch)

[ 96%] Building CXX object ApacheConnector/CMakeFiles/mod_poco.dir/src/ApacheConnector.cpp.o
/home/user/Documents/versioned/poco/ApacheConnector/src/ApacheConnector.cpp: In static member function ‘static void ApacheConnector::log(const char*, int, int, int, const char*)’:
/home/user/Documents/versioned/poco/ApacheConnector/src/ApacheConnector.cpp:157:51: warning: passing NULL to non-pointer argument 5 of ‘void ap_log_error_(const char*, int, int, int, apr_status_t, const server_rec*, const char*, ...)’ [-Wconversion-null]
   ap_log_error(file, line, level, 0, NULL, 0, text);
                                                   ^
/home/user/Documents/versioned/poco/ApacheConnector/src/ApacheConnector.cpp: In function ‘int ApacheConnector_handler(request_rec*)’:
/home/user/Documents/versioned/poco/ApacheConnector/src/ApacheConnector.cpp:196:37: error: invalid new-expression of abstract class type ‘ApacheServerRequest’
     r->connection->client_addr->port));
                                     ^
In file included from /home/user/Documents/versioned/poco/ApacheConnector/include/ApacheRequestHandlerFactory.h:15:0,
                 from /home/user/Documents/versioned/poco/ApacheConnector/include/ApacheApplication.h:15,
                 from /home/user/Documents/versioned/poco/ApacheConnector/src/ApacheConnector.cpp:12:
/home/user/Documents/versioned/poco/ApacheConnector/include/ApacheServerRequest.h:24:7: note:   because the following virtual functions are pure within ‘ApacheServerRequest’:
 class ApacheServerRequest: public Poco::Net::HTTPServerRequest
       ^~~~~~~~~~~~~~~~~~~
In file included from /home/user/Documents/versioned/poco/ApacheConnector/include/ApacheServerRequest.h:17:0,
                 from /home/user/Documents/versioned/poco/ApacheConnector/include/ApacheRequestHandlerFactory.h:15,
                 from /home/user/Documents/versioned/poco/ApacheConnector/include/ApacheApplication.h:15,
                 from /home/user/Documents/versioned/poco/ApacheConnector/src/ApacheConnector.cpp:12:
/usr/local/include/Poco/Net/HTTPServerRequest.h:69:15: note:    virtual bool Poco::Net::HTTPServerRequest::secure() const
  virtual bool secure() const = 0;
               ^~~~~~
ApacheConnector/CMakeFiles/mod_poco.dir/build.make:110: recipe for target 'ApacheConnector/CMakeFiles/mod_poco.dir/src/ApacheConnector.cpp.o' failed
