### ISSUE TITLE
Poco Documentation comments are confusing IDE's like Visual Studio

### ISSUE THREAD

**Issue by RobertAcksel** [pocoproject/poco#1409]
Poco Ducumentation comments of functions are always located under the function declaration. Ususally function comments are placed above the function declaration instead. This confuses IDE's like Visual Studio which will always show the wrong comment.

**Comment by obiltschnig** [comment]
This should probably be reported as a Visual Studio bug ;-)

**Comment by ibroheem** [comment]
Same with  Code::Blocks, I think the way the docs are styled (below declaration/defs as opposed to Doxygen above declarations) is the cause of the problem
![codeblocks-poco-doc](https://cloud.githubusercontent.com/assets/4117847/21498650/d886e956-cc2e-11e6-99c8-6a7975fa943b.png)

**Comment by ibroheem** [comment]
This get parsed correctly by the IDE.
![codeblocks-poco-doc-doxygen](https://cloud.githubusercontent.com/assets/4117847/21498811/55588ace-cc30-11e6-8879-215de80a2646.png)

**Comment by zosrothko** [comment]
Putting comments below the déclaration/definition is a choice of the designers of Poco, and IMO this is not gonna change... The PocoDoc tool is extracting the documentation  of all public classes/methods and format it to produce a nice hypermedia document. see https://pocoproject.org/docs/

**Comment by trzeciak** [comment]
Xcode has the same issues:
![screen shot 2017-12-12 at 17 27 44](https://user-images.githubusercontent.com/11998334/33896751-eae7818e-df63-11e7-9184-cfd01fb3ed01.png)

doxygen & Visual Studio & Code::Blocks & Xcode & more  **vs** _ choice of the designers of Poco, and IMO this is not gonna change..._

Maybe we should write to hypermedia, with petition to stop supports of comments below the déclaration/definition.

**Comment by aleks-f** [comment]
Not gonna change IMHO. We've had this discussion long time ago (in SourceForge era) and there must be a perl script somewhere that makes comments doxygen-compatible.

**Comment by obiltschnig** [comment]
So, to summarise things up:

I still think that the JavaDoc style of putting documentation before that thing that is being documented is flawed. What somewhat concerns me is that everyone blindly followed the JavaDoc style, probably because Doxygen also used it. Also, it's about time we get rid of HTML and other tool-specific (Doxygen) formatting syntax in documentation. Markdown is the way to go here. For me who, preferring reading header files, all this documentation written for the doc generation tool, not for a human reader, is a huge pain in the ass.

Tried to do it the IMO right way in POCO, with the method signature or class name first, followed by the documentation, which is used by the documentation generator, with minimum formatting markup. Makes it much more readable if you're looking at the source code, which I do most of the time.

Now, with 1000+ header files in Poco, changing the existing documentation style is not going to happen. So my suggestion would be to file a bug with IDE vendors to get their stuff together and support the Poco documentation style. Should not be too hard to recognise it - just look for "///"-style comments immediately following a declaration.

**Comment by zosrothko** [comment]
@obiltschnig The point opened here is IMHO not only for the documentation like doxygen, but also for the hoover and the auto completion feature as show above in the XCode window and Code::Block. Having such features avoid the developper to look at the source code in the include as you suggest  be the proper way. These are smooth features that avoid switching of window since the popup window disappears once a selection has been made. Having such features working in the 3 main C++ IDE would offer a real smooth integration of Poco making it a top portable C++ library. IMO, your position to put the comment below the fonction declaration is the rigth way, but unfortunatly, that's the other alternative which is the most commonly used. And asking for those IDEs to change their mind is IMHO not going to happen because of the existing thousands line of code with comments above the function declaration.

**Comment by obiltschnig** [comment]
I'm not expecting IDEs to switch to POCO's documentation format exclusively, but supporting both formats should not be that complicated.

**Comment by zosrothko** [comment]
How could they know if the proper documentation is above or under the function declaration just by parsing the source?

**Comment by obiltschnig** [comment]
For class-level documentation that's easy. For methods/functions - look at whitespace in combination with ///. Check if /// is immediately following the declaration (same or next line), with no empty line in between.

If they're lazy, check whether the header's full path includes "Poco" and if so, disable documentation parsing to prevent showing wrong documentation.
