### ISSUE TITLE
IPv6 DNS resolution fails on IPv6 only network

### ISSUE THREAD

**Issue by TcT2k** [pocoproject/poco#1449]
The IP sorting in `SocketAddress::init` (SocketAddress.cpp) breaks connectivity on an IPv6 only networks.

The DNS returns IPv4 and IPv6 addresses, but due to the sorting the IPv4 addresses (following the IPv6 addresses) are incorrectly chosen for connection. I think the sorting should simply be removed (fixed the issue for me) as the DNS will probably only return IPv6 addresses if the client has IPv6 connectivity.

I came across this issue when submitting an iOS app to the AppStore as Apple now tests your apps on IPv6 only networks.

**Comment by obiltschnig** [comment]
Too late for 1.7.6, as this may break existing code. Fixed this in commit 6195c97a868b7f61f5ad993f5a90eccb6a3df339 in develop branch. Let's give it a try there.

The sorting was added in 2011 for release 1.4.2. From CHANGELOG:
```
- Poco::Net::SocketAddress: when there is more than one address
  returned by a DNS lookup for a name, IPv4 addresses will be 
  preferred to IPv6 ones.
```

The fix was done in response to a customer issue with a DNS server returning both an IPv6 address and an IPv4 address, with the IPv6 address first. However, the client failed to connect to the IPv6 address.

**Comment by TcT2k** [comment]
Thanks for the quick reply. I've already tried without the sorting and that fixes the issue for me.

From a pure hypothetical point it would make sense to me that a DNS in a network without IPv6 connection would not resolve names to IPv6 entries.

**Comment by noangel** [comment]
Thanks for posting fix! I think we have the same issue in our library using Poco, and now it failed to pass Apple check under iOS 10. Looks like DNS problem when using IPv6 network. Cannot connect to server any more. It's strange that under iOS 9.x it worked but broke since 10.0. Probably some OS socket code changes.
I'll apply fix to my older library source, and report results.

**Comment by zosrothko** [comment]
I think this fix in ``` Net/src/SocketAddress.cpp```is  too much static
```
+#if defined(POCO_HAVE_IPv6) && !defined(POCO_SOCKETADDRESS_DONT_PREFER_IPV4)
```
because it won't apply in packaged Poco for Fedora Ubuntu or WIndows. I would suggest to make this choice against a environment variable as POCO_DSN_RESOLUTION with values (IPV4, IPV6) with a default at your choice.
