### ISSUE TITLE
Fix Socket::select() epoll and poll implementations.

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1459]
As discussed in #1458, there are multiple issues in the epoll and poll-based Socket::select() implementation:
- struct epoll_event eventsIn is allocated on the stack
- POCO_INVALID_SOCKET is not handled in poll implementation
- poll code needs some review

**Comment by rohitgoyal2112** [comment]
Hi @obiltschnig , I was trying to compile the source for macOS using the flag POCO_HAVE_FD_POLL but select() does not use the poll implementation. Is this a known issue or am i doing something wrong?

**Comment by obiltschnig** [comment]
I would not recommend using `POCO_HAVE_FD_POLL` at this time. Release 1.8 has a new `PollSet` class, which works much better than `select()` with a large number of sockets. Only drawback for now is that SocketReactor has not been changed yet to use it.

**Comment by aleks-f** [comment]
`Socket::select` could be nicely tidied up using `PollSet`, to look like this:
```c++
int Socket::select(SocketList& readList, SocketList& writeList, SocketList& exceptList, const Poco::Timespan& timeout)
{
	PollSet ps;

	for (const auto& s : readList)
		ps.add(s, PollSet::POLL_READ);
	readList.clear();

	for (const auto& s : writeList)
		ps.add(s, PollSet::POLL_WRITE);
	writeList.clear();

	for (const auto& s : exceptList)
		ps.add(s, PollSet::POLL_ERROR);
	exceptList.clear();

	PollSet::SocketModeMap sm = ps.poll(timeout);

	for (const auto& s : sm)
	{
		if (s.second & PollSet::POLL_READ)
			readList.push_back(s.first);
		if (s.second & PollSet::POLL_WRITE)
			writeList.push_back(s.first);
		if (s.second & PollSet::POLL_ERROR)
			exceptList.push_back(s.first);
	}

	return static_cast<int>(sm.size());
}
```

Except that `PollSet`, as it is now, completely overwrites the mode for the socket on `add()` or `update()`; eg. if you add a socket monitored for `write`, then add that same socket monitored for `read`, it will be only monitored for `read` - in order to be monitored for read and write, both flags must be added at once. Aside from being non-intuitive, this creates a complication for the `Socket::select()` implementation with `PollSet` - one would have to cross-examine all fd_sets, find duplicates, and set modes acordingly, obviously a performance killer.

So, I'm not sure which way to take this issue. Probably best would be to fix `PollSet`; it is doable without breaking existing code (syntax and semantics) by adding `bool overwrite = true` parameter to `PollSet:add()` and `update()`

@obiltschnig

**Comment by obiltschnig** [comment]
For now, let's leave `Socket::select()` as is, and maybe even deprecate it. Get people to use `PollSet`, as it's much better suited, especially with higher number of sockets.
