### ISSUE TITLE
AbstractConfiguration::getUInt does not parse hex numbers

### ISSUE THREAD

**Issue by IronCaterpillar** [pocoproject/poco#1462]
The above method is described as follows: 
_// Returns the unsigned int value of the property with the given name.
/// Throws a NotFoundException if the key does not exist.
/// Throws a SyntaxException if the property can not be converted
/// to an unsigned int.
**/// Numbers starting with 0x are treated as hexadecimal.**
/// If the value contains references to other properties (${<property>}), these
/// are expanded._
but in fact the conversion is done by invoking  `NumberParser::parseUnsigned` which calls`strToInt(s.c_str(), value, NUM_BASE_DEC, thSep);`. As a result we get **Syntax** exception.

**Comment by obiltschnig** [comment]
getUInt() should call parseUInt() instead of NumberParser::parseUnsigned().

**Comment by cngzhnp** [comment]
Also it should be fixed for 64-bit integers too. By the way, why AbstractConfiguration class has a function  to parse in implementation side? I think, parseUInt() function moved to NumberParser class and should be called from this class. Otherwise, parsing process should be lower layer than AbstractConfiguration class.
