### ISSUE TITLE
POCO websocket receive failed for more than 15K byte datasize

### ISSUE THREAD

**Issue by vinod82** [pocoproject/poco#1469]
I am trying to receive a larger chunk of binary data ( 25000 ) with receiveFrame() API. 
I see that, when socket is operating in non-blocking mode, Frame received is corrupted . It works fine when socket is operating in blocking mode with larger timeout. Has anybody faced the same ?

**Comment by obiltschnig** [comment]
The WebSocket class is not designed to work with non-blocking sockets.

**Comment by waldheinz** [comment]
> The WebSocket class is not designed to work with non-blocking sockets.

I guess that's not really obvious because this class has an `setBlocking()` method. If the Poco class structure does not allow to get rid of that method it would probably be a nice touch to let it throw some exception on attempt to set it non-blocking. I just spent the better part of a day debugging until i stumbled upon this issue. :sob:
