### ISSUE TITLE
available() returns 0 on a secure websocket when data is available for reading.

### ISSUE THREAD

**Issue by crosscode-nl** [pocoproject/poco#1482]
I used version 1.6.0 for a while and that version worked. I tried to migrate to the latest 1.7.6 version, but then I found available() no longer worked as it should. It will always return 0. 

I use a WebSocket in combination with a HTTPSClientSession. 

I tested all versions and found that 1.6.1 still works. I seems broken since 1.7.0.

I use it on linux/ubuntu.

**Comment by micheleselea** [comment]
Is not a WebSocket issue, is a generic behavior of SecureSocket. I always found this on all version of poco lib but I do not think it's a Poco problem. I think the problem is that when you have a secure socket the available is done not with a select but with an OpenSSL function: this function return >0 only if you have sine decede data in the stream. But sometime you have some raw data on the socket not yet decoded (because perhaps you do not have all the bytes OpenSSL need for decoding) so the available data is = 0 even if you have unread bytes.
In that situation I sometime use something like

if available==0 and socket is secure
check with a socket().poll if it is readable
try read some bytes and go on

**Comment by obiltschnig** [comment]
@micheleselea: your analysis is basically correct. The previous behavior (in 1.6.0) was incorrect and caused some issues, that's why it has been changed to current behavior. The definition of available() is that it returns the number of bytes that can be read without blocking. The issue with OpenSSL is that even if there may be bytes available from the socket, these may not be enough to decrypt the next encrypted block, potentially causing the next receiveBytes() to block unexpectedly.

**Comment by crosscode-nl** [comment]
I don't understand it yet. I know there is data available. Multiple frames are pending to be read. So I call select(), and see that I can read, I call available() and see the amount of bytes I can read is 0. 

I will loop through this every now and then, but available() always stays 0. If I ignore this fact, I can read the data just fine. 

Shouldn't it just become larger than 0, or does the decoding only start on a call to receiveBytes?

**Comment by micheleselea** [comment]
with SecureSocket you cannot have the correct ammount of data to be read until you read it. It's the available method that you should avoid in SSL connection, just read it with a timeout

**Comment by obiltschnig** [comment]
With a normal StreamSocket, available() returns the number of bytes that are waiting in the system's socket buffer to be read (`ioctl(FIONREAD, result);`). With a SecureStreamSocket, available() now returns the number of bytes already decrypted (during a previous receive), waiting in the OpenSSL buffer to be read (SSL_pending()).

The problem this solves is as follows: I had a case involving a web socket where I would read in a loop testing for `socket.available() > 0 || socket.poll(...)`. In that particular case, socket.available() was 0, but there was still data to read in the OpenSSL buffer (SSL_pending() would have returned something > 0). Therefore, the code was blocking in poll(), waiting for more data, although there was decrypted data available in the OpenSSL buffer, leading to some issues.

**Comment by micheleselea** [comment]
available() could does an "OR" of the 2 two different method, but, as you said before, available should return the number of bytes you can read without blocking

**Comment by crosscode-nl** [comment]
If I call receiveFrame() and I don't want it to block, what is the right method to do so? 

available() won't help me here, so I call select or poll... but does that guarantee there is a complete decrypted websocket frame available? Or could it, in theory, block? (And block means a potential DOS situation...)

**Comment by obiltschnig** [comment]
I'd do a poll() in combination with a short read timeout on the socket. So you'll only read a frame when poll() indicates that data is available, and you limit the time you wait for the frame with the socket receive timeout. You cannot guarantee that a complete decrypted frame is available. Furthermore, OpenSSL may need additional receive or send operations (in case of a renegotiation) while you receive the frame. A solution for this would be a non-blocking WebSocket implementation. However, non-blocking sockets are currently not supported.
