### ISSUE TITLE
Poco::Timer vs Poco::Util::Timer

### ISSUE THREAD

**Issue by icehockeystar** [pocoproject/poco#1505]
Hi, a small question here, why are there two timer classes in Poco? I used Util::Timer once it turned out the Timer doesn't work if I run my serverapplication with --daemon flags. I migrated to Poco::Timer and there it works without problems. Where the difference between them?

**Comment by obiltschnig** [comment]
Poco::Util::Timer was added later and was created to allow having multiple timer tasks within a single timer thread.
The issue you see with daemon is because your Poco::Util::Timer is probably a member of your Application class. Poco::Util::Timer will create a thread in its constructor. This happens before the fork(), so that timer thread is lost in the forked daemon process. Solution is to create the Poco::Util::Timer with new in main() or initialize() (after calling base class initialize()).
