### ISSUE TITLE
Building with OS X 10.12 SDK and 10.7 deployment target without libc++ fails

### ISSUE THREAD

**Issue by TcT2k** [pocoproject/poco#1536]
The changes to _AtomicCounter.h_ in 19c0b38bf89af7a4bf190e2e062e536e5974347b causes building to fail with older deployment targets, in my case 10.7.
`atomic` can not be found with the lower deployment target without libc++.

The `#ifdef` probably needs to be extended to check for libc++

It compiles fine as soon as I remove the definition of `POCO_HAVE_STD_ATOMICS`

**Comment by wtextor** [comment]
Actually the fix should be to use the recommended way of naming specifying the SDK version numbers. This means that instead of `__MAC_10_12` the value `101200` should be used. The fixed line 27 should read (everything on one line!):
`#if __MAC_OS_X_VERSION_MAX_ALLOWED >= 101200 || __IPHONE_OS_VERSION_MAX_ALLOWED >= 100000 || __TV_OS_VERSION_MAX_ALLOWED >= 100000 || __WATCH_OS_VERSION_MAX_ALLOWED >= 30000`
