### ISSUE TITLE
Unable to use Poco on macOS 10.12

### ISSUE THREAD

**Issue by pqvst** [pocoproject/poco#1551]
I'm completely stuck after having upgraded to macOS 10.12 (while targeting an older version of macOS).

* I'm unable to build with Poco 1.7.6 becacuse of #1453
* Poco 1.7.7 fixes #1453, however I'm unable to build with it because of #1536

So, now I'm stuck and can't build my application. Is there any relatively easy workaround to get either 1.7.6 or 1.7.7 to work, with the code base as it is right now (without modifications). For example, using some defines or whatever? Otherwise I guess I'll have to hack something together in a fork..

**Comment by obiltschnig** [comment]
Try the poco-1.7.8 branch, which has the fix for #1536. Also, I have updated the Darwin build configurations. You can use the Darwin-clang (and Darwin32-clang) build configurations to build for 10.7.

I have only been able to test this on 10.11.6 with Xcode 8.2.1, but it should work on 10.12 also, since it has the same toolchain.
