### ISSUE TITLE
can support gbk to utf8??

### ISSUE THREAD

**Issue by byteman** [pocoproject/poco#1595]
i want convert from gbk to utf8 by TextConverter, but i can not find the gbk TextEncoding

**Comment by JiekeZhu** [comment]
Up. Same request.

**Comment by tigerlee** [comment]
+1

**Comment by aleks-f** [comment]
> i want convert from gbk to utf8 by TextConverter, but i can not find the gbk TextEncoding

We welcome contributions. Implement it, write tests, and send pull request. We can also be hired to do it for you.

> we need to convert from ASCII string which could be with GBK string to UT8 string

I'm not understanding what does this mean. GBK is Chinese, right? ASCII is, well - ASCII, ie. American. So, how can an ASCII string be GBK?

**Comment by tigerlee** [comment]
> i want convert from gbk to utf8 by TextConverter, but i can not find the gbk TextEncoding

Since `CP936` is an alias of `GBK` and `GBK` is a superset of `GB2312`, and Poco supports convert from `cp936` to `UTF-8`, so I think this issue should be closed.

Here is the code:

```c++
Poco::Windows936Encoding cp936;
Poco::UTF8Encoding utf8;
Poco::TextConverter converter(cp936, utf8);
std::string src = "你好";
std::string dst;
converter.convert(src, dst);
```
`dst` is a `UTF-8` string now.

[reference](https://zh.wikipedia.org/wiki/%E6%B1%89%E5%AD%97%E5%86%85%E7%A0%81%E6%89%A9%E5%B1%95%E8%A7%84%E8%8C%83#%E8%88%87CP936%E5%AD%97%E7%A0%81%E8%A1%A8%E6%AF%94%E8%BC%83)
