### ISSUE TITLE
Statement::execute() affected row count incorrect for ODBC impl with bound parameters

### ISSUE THREAD

**Issue by nick42** [pocoproject/poco#1670]
The documentation states that ::execute() returns the affected row count, but this appears to be inaccurate. In specific, ODBCStatementImpl::doBind() sets the _affectedRowCount member to "1L" (hardcoded result from Binding::numOfRowsHandled()) if it is otherwise "0". This cases the Statement::execute() method to return "1" in cases where a parameter was bound for the query, but no rows were actually affected.

Sample repro (case in which I found the issue):
Query is something like "DELETE FROM table WHERE field < ?", with bound parameter for field, and query which does not delete any rows. Statement::execute() will return "1".

**Comment by nick42** [comment]
Note that Statement::wait() returns the correct value ("0") in this problematic case. I'd suggest perhaps a unit test case to catch this (not sure if Poco project has unit tests, though).

**Comment by obiltschnig** [comment]
@aleks-f Have you looked into this?

**Comment by aleks-f** [comment]
I looked into it and I can think of no solution other than a significant modification of how things work - as things are now, the affected number of rows will always be 1 when there are only clause parameters used outside of the statement string.

Explanation:

There are two types of inbound (ie. `use()` or `bind()` arguments) values:
1) values that actually go in the database (eg. `"INSERT INTO Table VALUES(?)", use(x)`)
2) values that define a clause (`"DELETE FROM table WHERE field < ?", use(y)`)

Both types are passed in the same way and there's currently no way to distinguish between them internally. We base the number of affected rows on the arguments passed to `use`, `bind`, `into`, etc. This is reliable in most cases, because if we are inserting a single int then there will be one row affected, or if we are sending in a vector of 10 members, there must be either 10 rows affected or an exception.

**But in case 2), this is obviously wrong whenever the number of affected rows is different than 1.**

In theory, there is a way to find the number of affected rows from the driver -  ODBC spec says driver _may_ provide information on affected rows via `SQLRowCount`. However, in practice this is a "hit and miss" and we only attempt it if there were no external bindings provided that tell us how many rows we are affecting.

A solution would be to introduce another keyword to distinguish between I/O and clause parameters . Eg. `"DELETE FROM table WHERE field < ?", clause(y)` would allow us to leave the affectedRows at zero and rely on the driver (which may still be wrong from my experience - eg. MySQL driver will for some reason return 1 even when multiple rows are deleted and `SQLRowCount` is called immediately after `SQLExecute`).

There may be a better solution, but I do not see it at this time.

**Comment by bmulder-innoseis** [comment]
Do you have a workaround for this issue? I am trying to select a row from a table, for example with the following code:
```
SomeType result {};
auto statement = (session << "SELECT * FROM table WHERE field = ?", into(result), use(value));
size_t rows = statement.execute();
```
now since rows will always be 1 in my case, how can I know if my result variable contains any meaningful data?
because if there is no corresponding row in the database, the result variable will be initialized with default values. But these default values might be correct data (e.g. zero). How can I know if there was anything found?
