### ISSUE TITLE
Include test scripts in release packages

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#1699]
build/script/runtests.sh
build/script/runtests.cmd
build/script/runtests2.cmd

**Comment by zosrothko** [comment]
Can one add also the `PocoDoc` on the `world` release so that the documentation be build everyday on the target packing system Fedora/Ubuntu (The `PocoDoc, CppParser and PDF` components will not be released by construction). This means also to publish the `world` release as well as the `all` release
