### ISSUE TITLE
Support for peek function in SecureSocketImpl

### ISSUE THREAD

**Issue by buddingspacer** [pocoproject/poco#1814]
SecureSocketImpl to support the ssl_peek function, since applications may choose to peek into a request ,
or please suggest otherwise

**Comment by micheleselea** [comment]
I think you should read bytes and put in your internal buffer and than make your "own peek function" from your buffer. Secure socket has some strange behavior even in available, because the decrypt process take place when you call read, so you cannot know in advance how many byte you can read from socket until you read at least 1 byte.
So you probably should just read and append to your buffer and than doing something with it

**Comment by aleks-f** [comment]
correct, SSL can also be re-negotiating on its own and indicate SSL_WANT_READ when there's really no payload available

**Comment by buddingspacer** [comment]
But imagine a use -case i dont want to actually read fromsocket, butjust peek into contents to make a decision to route the socket based on it contents.
Say i have a webscoket server and webpage both listening on same scoket. Here i have to peek into a packet before decidng either to Websocket Server or webpage based on URI. How to acheive this with current POCO ?

**Comment by micheleselea** [comment]
You should create a poco HTTPServer and use it with a SecureServerSocket.
After that HTTPServer do the job for you, it will call createRequestHandler of your HTTPRequestHandlerFactory and than you can use request.getURI() to get the requested uri.
Look at the HTTPSTimeServer sample
