### ISSUE TITLE
How to set Poco to process three.js ?

### ISSUE THREAD

**Issue by Diablo550** [pocoproject/poco#1833]
I have Poco HTTPFormServer running the example code ok.
I'm using mustache to format the page, (maybe this is the problem ?)
I have three.js compiled by npm/node on ec2 ubuntu
on the Firefox debugger, I can see the GTE http://127.0.0.1/three.js is successful
but then there is an error:
      SyntaxError:        expected expression, got '<'
      ReferenceError:  THREE is not defined

how do you serve/process three.js ? 
is there an example for this type of service ?
confused noob :(

**Comment by aleks-f** [comment]
The problem has nothing to do with poco because server knows nothing about the internal structure of the web application - it's all in html and js files. So, you have to provide a HTTP handler that will return files that browser needs to run the application; modify your RequestHandlerFactory to spawn a handler that returns the requested files and it will work. 

I'm not sure why npm/node - I'd just copy the three, moustache etc source trees to a place where server can see it and serve the files from there.

**Comment by Diablo550** [comment]
Hi, that sounds excellent, but how to do ?

I checked my code, this function RequestHandlerFactory  is empty.
Could you point me to an example ?

struggling noob :(

**Comment by fbraem** [comment]
My project [MQWeb](http://www.mqweb.org) has a request handler that can serve static files like scripts, images, html, etc ... Here's the [source code](https://github.com/fbraem/mqweb/blob/develop/MQWeb/src/AppRequestHandler.cpp).

**Comment by Diablo550** [comment]
thanks, looks great..
