### ISSUE TITLE
Android compile error -- 'pthread_condattr_setclock' undefined in 'Event_POSIX.cpp'

### ISSUE THREAD

**Issue by alfeng** [pocoproject/poco#1836]
Using Poco v1.7.8 with Android NDK r15c (building for API level 19), I get the following error compiling 'Event_POSIX.cpp'.

`Foundation/Event_POSIX.cpp:72:6: error: use of undeclared identifier 'pthread_condattr_setclock'; did you mea 'pthread_condattr_setpshared'? if (pthread_condattr_setclock(&attr, CLOCK_MONOTONIC)) ^~~~~~~~~~~~~~~~~~~~~~~~~ pthread_condattr_setpshared Android/NDK/build//../sysroot/usr/include\pthread.h:128:5: note: 'pthread_condattr_setpshared' declared here int pthread_condattr_setpshared(pthread_condattr_t* _Nonnull, int); ^ 1 error generated.
`
This appears to be similar to GH [#1403](https://github.com/pocoproject/poco/issues/1403), which was labeled as "fixed" by v1.7.8.  Did something change in NDK r15c to cause the issue to resurface?

If I change my API level to 21, the problem of course goes away.  It also goes away if I switch back to NDK v13, though it's not as clear (to me) why.

Is API level 19 using these versions of Poco & NDK supported?

**Comment by Bjoe** [comment]
Since r15, google use in the NDK as default to the Unified Headers. Set "[deprecated headers](https://android.googlesource.com/platform/ndk/+/ndk-r15-release/docs/UnifiedHeaders.md#using-unified-headers)" to true at compile time to enable the old headers.
A pull request #1983 is created to fix this issue here.
