### ISSUE TITLE
Make network address family resolution a runtime choice

### ISSUE THREAD

**Issue by zosrothko** [pocoproject/poco#1871]
Hello

Refering the thread in this issue [#1866](https://github.com/pocoproject/poco/pull/1866) refering this [change](https://github.com/pocoproject/poco/commit/6195c97a868b7f61f5ad993f5a90eccb6a3df339#diff-2ce271e0dc976c018a34a8166b332a03L253) I would suggest to make it dynamic depending on a environement variable --let say `POCO_ADDRESS_FAMILY_PREFERENCE`, with a default value to `IPv4 `-- so that people could choose their stategy. Bundling this choice into the code seems to me restrictive. Main advantage would be to let `localhost`  be resolved to `127.0.0.1` by default on `IPv4 ` network.

**Comment by micheleselea** [comment]
yes probably you are right, so we can chose if I need to accept (or connect to) socket on locahost IPv4 or ::1 (localhost) IPv6

**Comment by obiltschnig** [comment]
The reason for the change was #1526.

Generally I'd say we should honour the order of IP addresses we receive from DNS. Unfortunately that has the nasty side effect that in many cases localhost will resolve to ::1 instead of beloved 127.0.0.1. 

I'm in favour of providing a runtime choice, but IMO the default should be to respect the DNS ordering.
