### ISSUE TITLE
How can I make httpserver Asynchronous?

### ISSUE THREAD

**Issue by jinyuelong** [pocoproject/poco#1879]
Hi,
I'am using Poco to implement a httpserver, and my httpserver is kind like a proxy, it receives the request from A and based on that request, it will connect another Website and get some data from it, if the data is received, I will continuely send to the A, so here is my problem:
my current implemention is do all those jobs (read from A -> connection to WWW -> get data from WWW -> send to A) on handleRequest synchronous, but when thread is reading from WWW ( it takes a while ), it will hang there and low down the QPS so much, is there any way to make it Asynchronous？
thanks very much, i'm new to Poco and sorry for my English:)

**Comment by aleks-f** [comment]
There is no "out of the box" async http client or server in POCO. But, if I understand it correctly and your proxy is "blindly" passing data back to clients, then you could minimize the time spent in handler by introducing a custom long-living object, instantiated and held by the handler factory. Let's call this object `ProxyObject`. ProxyObject would contain a list of outstanding requests and their sockets (added by handlers, cleaned by ProxyObject when done), [Socket::select()](https://github.com/pocoproject/poco/blob/poco-1.7.8/Net/src/Socket.cpp#L77) (in spite of the name, it will `epoll` or `poll` if available on the platform) and send available data chunks back to clients.

So, the only thing a handler would do in this scenario is sen the request and add necessary information to the `ProxyObject` for receiving response and responding to client. ProxyObject would have to pause to accept new items (you can even have an intermediate buffer object here to minimize the blocking between handlers and ProxyObject), but would otherwise continuously loop (in its own thread) to receive and pass back the data.

Depending on how many clients you are serving, you still may congest the server during clients requests outburst - handlers are threads and threads are expensive and of limited availability.

**Comment by jinyuelong** [comment]
@aleks-f thanks a lot, it's very helpful ^_^

**Comment by aleks-f** [comment]
FWIW, see #1939 and an early [attempt](https://github.com/pocoproject/poco/commit/a03a3f95cb5238d2e6c081a923bc3bd0ed024d1a#diff-ffb14f924de79f5269fe1d65b9e76662R1) for reactor-based HTTP server

**Comment by feixintianxia** [comment]
Unfortunately, the Poco HTTP server cannot implement asynchronous responses.
