### ISSUE TITLE
FTPClientSession anonymous user

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#1907]
I check the FileZilla client behavior when you do not set username. It send anyway a "USER anonymous" command with a password (if server required) anon@host
Do you think it's correct? Currently our FTPClientSession do not send anonymous username, but simply do not send USER command if you do not set user. What do you think @obiltschnig @aleks-f ?

**Comment by obiltschnig** [comment]
Back in the old days it was common to send your email address as password for the `anonymous` account. In the end, what's correct depends on the specific configuration of the FTP server you're talking to, and whether there's an `anonymous` account at all. So not sure if we should default to `anonymous` since whatever we chose as default password will likely upset someone.

**Comment by micheleselea** [comment]
Ok, but because now we do not send any password whatever we choose is the same isn't it?
I don't know if it's standard to login in a FTP server without username specification, even if you are anonymous. Don't know, probably.
Anyway if we decide to leave the clientftp without calling login when we have empty username, we should deal with the socket created from outside and given to the client and open() connection with an empty username.
So something should be fixed, anonymous or not: if we take a decision about I can send a pullrequest about

**Comment by micheleselea** [comment]
ok let's do this: do not modify FTPClient to send anonymous user (even I do not figure out what should be the standard) but I make a pull request to fix the case we use external socket with a subsequent open() call without username
