### ISSUE TITLE
JSON::Parser has problems parsing large numbers

### ISSUE THREAD

**Issue by sgorsh** [pocoproject/poco#2009]
### Expected behavior
During testing I've found out that Poco::JSON::Parser has problems parsing large numbers, which are produced by Chrome's `JSON.stringify`. Parsing of the same number works in scientific notation.

Chrome produces these outputs:
`JSON.stringify({"n":10000000000000000000}) => "{"n":10000000000000000000}"`
`JSON.stringify({"n":100000000000000000000}) => "{"n":100000000000000000000}"`
`JSON.stringify({"n":1000000000000000000000}) => "{"n":1e+21}"`
`JSON.stringify({"n":10000000000000000000000}) => "{"n":1e+22}"`

### POCO tests:
_Number: 1e19_
`JSONParser.parse("{\"n\":10000000000000000000}").extract<Object::Ptr>();`
`JSONParser.reset();`
Works OK.

`JSONParser.parse("{\"n\":1e19}").extract<Object::Ptr>();`
`JSONParser.reset();`
Works OK.

_Number: 1e20_
`JSONParser.parse("{\"n\":100000000000000000000}").extract<Object::Ptr>();`
`JSONParser.reset();`
**Exception: Not a valid unsigned integer**

`JSONParser.parse("{\"n\":1e20}").extract<Object::Ptr>();`
`JSONParser.reset();`
Works OK.

_Number: 1e21_
`JSONParser.parse("{\"n\":1e21}").extract<Object::Ptr>();`
`JSONParser.reset();`
Works OK.

### POCO version
1.8.0.1

### Compiler and version
Visual Studio 2017 15.4.4

### Operating system and version
Windows 10 x64 1709

**Comment by obiltschnig** [comment]
@aleks-f Could this be an issue with pdjson?

**Comment by aleks-f** [comment]
no, it is [NumberParser](https://github.com/pocoproject/poco/blob/develop/Foundation/src/NumberParser.cpp#L63) related - `1e20` is larger than max uint64. I'll fix it.

**Comment by aleks-f** [comment]
Looking at it, I'm not sure what to do. 

JSON has [no number limit ](https://stackoverflow.com/a/13502497/205386)- it is whatever a platform supports.
Traditionally, we [support integers](https://github.com/pocoproject/poco/blob/poco-1.8.0/JSON/testsuite/src/JSONTest.cpp#L277), up to the platform limit and [fail otherwise](https://github.com/pocoproject/poco/blob/poco-1.8.0/JSON/testsuite/data/invalid/too-big-positive-integer/input).

We could say all numbers are floating point, but then integers can lose precision - we advertise support for something we can't support.

Alternatively, we can support bigint, but that's not a small feature to add. In any case, I'd document the limitation for 1.8.x and (perhaps) do something about it at some point later in 2.x

**Comment by aleks-f** [comment]
Somewhat related is #1927 - by relying on double-conversion, we turn floats with `.0` into integers.

**Comment by obiltschnig** [comment]
I'd suggest trying to parse as Int64 first, if that fails, try double. See also my comments in #1927.

**Comment by aleks-f** [comment]
We do [something like that](https://github.com/pocoproject/poco/blob/poco-1.8.1/JSON/src/ParserImpl.cpp#L188-L200) currently - we look for `e`, `E`, or frac separator,  and parse as double if either is found, otherwise try `Int64`, if that fails try `UInt64`, otherwise throw. I'd just leave it as is and document that we currently do not support numbers larger than what platform allows.

**Comment by sgorsh** [comment]
My opinion is that it would be nice to add option to JSON parser to treat all numbers as floating point (double) by default, to have compatibility with JSON produced by browsers. In Javascript, all numbers are represented by 64-bit floating point.

**Comment by aleks-f** [comment]
I'm not particularly impressed with what javascript does.
![image](https://user-images.githubusercontent.com/2429093/33226044-6658e21e-d149-11e7-961a-cbecc18c07e8.png)
But, ok - an alternative number handling mode of operation would not be a problem as long as it is optional and we leave the current as model default.

If you want it quick, send a pull with test case and we'll review it.
