### ISSUE TITLE
Logging: Remove raw pointers from public interfaces

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#2076]
Remove raw pointer arguments and return values for `Channel` and related objects.

  1) For all methods taking raw pointer arguments, create overloads taking `Poco::AutoPtr`.
  2) Change return value types from raw pointers to `Poco::AutoPtr`. 
  3) In a future version remove methods taking raw pointer arguments.

**Comment by aleks-f** [comment]
> For all methods taking raw pointer arguments, create overloads taking Poco::AutoPtr.

as it currently stands in #2189 , I have just kept AutoPtr interfaces - having both means having to carry additional internal container (eg. LoggerMap), or otherwise keep track of which pointers came in as raw ones and which as AutoPtr; too much trouble, IMO the best opportunity to break backwards compatibility is a major release like this one (we're doing it elsewhere, too eg. Data->SQL), just document it clearly and prominently

**Comment by aleks-f** [comment]
@obiltschnig this was released right?
