### ISSUE TITLE
On OSX High Sierra Xcode 9.2 compilation fails

### ISSUE THREAD

**Issue by Nechoer** [pocoproject/poco#2107]
"./configure --config=Darwin64-clang-libc++" and "make" should work

make fails with /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:15: fatal error: 
      'string.h' file not found

1.8.01 and 1.8.1

 Xcode 9.2 command line tools installed

 OSX High Sierra  10.13.2

**Comment by obiltschnig** [comment]
Something wrong with your Xcode installation then. Have you installed the Xcode command-line tools package?

**Comment by Nechoer** [comment]
Oops, thank you, it seems when I updated XCode I did not reinstall the latest command line package.. I should have thought… possibly it was using previous versions.
sorry for the waste of bandwidth ..

**Comment by waTeim** [comment]
I'm late to this discussion, but I believe I know the cause of this, for I have experienced the same problem.  It's Apple's fault.  The cause is that when Xcode 9 is installed from scratch on High Sierra -- now this might be Xcode9 or High Sierra or a combination.  I have I only experienced the combination -- then `/usr/include` is not installed properly (it's empty), even when (technically) *command line tools* is installed.  There are 2 solutions.   

One is to simply change 2 lines in `Darwin-clang-libc++` from

    CC      = $(shell xcrun -find clang)
    CXX     = $(shell xcrun -find clang++)
to

    CC      = clang
    CXX     = clang++

This will cause the include path to be silently augmented to also include where **string.h** really is located.

And of course, the 2nd (better) approach is to blindly re-install command line tools even if it is already installed.  When it is re-installed, at that time, `/usr/include` is populated.

**Comment by michaeladamkatz** [comment]
@waTeim thank you very much. This was a life saver. @obiltschnig @aleks-f please include this information from @waTeim in the build instructions. My understanding is that the problem/fix is specific to Darwin-clang-libc++ (which is what I'm using).

**Comment by roelvz** [comment]
Here's my two cents on this: @waTeim's suggestion only worked partially for me. I still got the following warning and error:

```
clang: warning: treating 'c' input as 'c++' when in C++ mode
invalid argument '-std=c99' not allowed with 'C++'
```

A solution for me was to to change a line in the same file (`Darwin-clang-libc++`) from:

`CFLAGS          = $(ARCHFLAGS) -std=c99`

to

`CFLAGS          = $(ARCHFLAGS) -x c -std=c99`

**Comment by fixedsys02** [comment]
@waTeim. Perfect solution for same issue on macos 10.14.4 / Xcode 10.1 / Mojave 10.14 CLI Tools.

**Comment by jacobsologub** [comment]
Just ran into the same issue on macOS 10.14.4 (18E226) with Xcode 10.2.1 (10E1001)

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
```
Running `xcode-select --install` reports `command line tools are already installed, use "Software Update" to install updates`

Re-installed the latest Command Line Tools from https://developer.apple.com/download/more/?=for%20Xcode

Got the same error, then ran this:
`$ open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

fixed.

**Comment by timgivois** [comment]
Running 
```
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```
and reinstalling the headers helped me. Thanks @jacobsologub
