### ISSUE TITLE
LINKER error trying to use POCO NET

### ISSUE THREAD

**Issue by rohaanhamid** [pocoproject/poco#2168]
#### Expected behavior
Poco Net should link successfully

#### Actual behavior
If I try to link to Poco Net in my project the compiler throws the following error:
"error LNK2001: unresolved external symbol pocoNetworkInitializer"

I am using VS 2008 and compiling for Windows CE. It compiled fine with VS 2013 for Windows.

*** EDIT: WORKAROUND
If anyone else is facing the same problem, setting the POCO_NO_AUTOMATIC_LIB_INIT preprocessor definition did it for me.  I think you just have to call initializeNetwork() before using any package in NET.

#### Steps to reproduce the problem
Compile a project linked to PocoNetmtd.lib

#### POCO version
1.8.1

#### Compiler and version
VS2008 SP1 for Windows CE

#### Operating system and version
Windows CE

**Comment by Ataginsky** [comment]
This solutions doesn't worked for me in WinCE 6.0 (target archi x86), VS **2005**.
The workaround was to completely comment `#if defined(POCO_OS_FAMILY_WINDOWS) && !defined(POCO_NO_AUTOMATIC_LIB_INIT) `section (from line 49) in **Net.cpp** file.

In the same time, I have zero problem with the same project but with target architecture ARM (so, diff SDK than x86 of course). I doesn't need to comment or setting POCO_NO_AUTOMATIC_LIB_INIT, it just link successfully.

**POCO version**
1.6.0

**Compiler and version**
VS200**5** SP1 for Windows CE 6.0

**Target architecture**
x86

**Comment by aaronamorim** [comment]
I can confirm this issue is still present in 1.9.0.  I can also confirm that windows CE/ARM builds and links fine.  The problem only appears to be in CE/x86.  I've confirmed that in both cases the macro expansion logic is identical.

**POCO Version**
1.9.0

**Compiler and version**
VS2008 SP1 targetting WEC7.0

**Target Architecture**
ARMV4I - Works
x86 - Link errors

**Comment by aleks-f** [comment]
The problem is possibly in [name decoration](https://github.com/pocoproject/poco/blob/poco-1.9.0/Net/include/Poco/Net/Net.h#L95-L107), but I'm not sure.

Confirmations that there is a problem are nice, but don't really address the problem. If someone would find the rot cause and send a fix pull, we'd gladly review and merge it.

**Comment by aleks-f** [comment]
alright, thanks; fixed for next release. we'll see if anyone complains ...
