### ISSUE TITLE
Run ping with custom timeout instead of the default 

### ISSUE THREAD

**Issue by dk1301** [pocoproject/poco#2177]
On one of my previous request I asked for the possibility of running ping with custom data size (Run ping with custom data size #1912) and as I have seen is going to be fixed for release 2.0.0.
Is this implementation going to include custom timeout as well because it would be very handy for measurement apps in case the response take too much time for the timeout (in case of IcmpClient 50000)  to be triggered. I assume that the default refers to 50 seconds because I haven't find this info somewhere.

**Comment by aleks-f** [comment]
Custom dataSize, ttl, and timeout capabilities were all added in [ping](https://github.com/pocoproject/poco/commit/03e97dd0f721a0ed36317d5ec31feeef99392bd8#diff-8a3d365d15764b8c990996f598ca1d28R65) and [ICMPClient](https://github.com/pocoproject/poco/commit/03e97dd0f721a0ed36317d5ec31feeef99392bd8#diff-1c8f5b0964f53abbe8d9b4bfc9d306d6R37). 

Is timeout not working for you?

**Comment by dk1301** [comment]
I'm currently using poco version 1.7.8 p2. From which version on is it supported because I assumed that it will be supported on version 2.0.0?

**Comment by aleks-f** [comment]
you can try to cherry pick it back into 1.9.0 branch for the next release

**Comment by dk1301** [comment]
Sorry for the inconvenience but since I haven't dealt before with cherry pick and pull request procedure are there any instructions I can follow in order to achieve this? In general you mean that I should wait for the release 1.9.0 or I have misunderstood ?

**Comment by aleks-f** [comment]
(start with github web interface)
1) fork the poco repository on github 
(switch to your local machine now)
2) git clone https://github.com/dk1301/poco
3) cd poco
4) git checkout poco-1.9.0
5) git cherry-pick 03e97dd0f721a0ed36317d5ec31feeef99392bd8
6) if there are conflicts, fix them, make sure everything builds and tests pass
7) git push
(switch to github web now)
8) send pull request to poco repository (poco-1.9.0 branch) on github

if you want your requests addressed faster, spend some time familiarizing with git and github, so you can help us help you; otherwise you have to wait until one of us has some spare time - a good search engine is your friend

**Comment by aleks-f** [comment]
> you mean that I should wait for the release 1.9.0

yes, if changes are cherry picked from develop to 1.9.0 branch. otherwise it will be 2.0

**Comment by dk1301** [comment]
Thanks for the support I'll try that

**Comment by aleks-f** [comment]
https://github.com/pocoproject/poco/commit/2ff645d5987baf4758435eba464bcb3e93ff44b4
