### ISSUE TITLE
Logging std::wstring or wchar_t

### ISSUE THREAD

**Issue by KevDi** [pocoproject/poco#2181]
#### Expected behavior
Try to print Logging Message to Console. The Message is a `std::wstring`.
#### Actual behavior
Did not compile because `logger.information()` expected a `std::string` not a `std::wstring`.
#### Steps to reproduce the problem
This is a simple Example:
```cpp
int main(int argc, char** argv)
{
        Logger& logger = Logger::get("Testlogger");
        std::wstring WStringMessage = L"Message as a WString";
        std::string StringMessage = "Message as a String";
        //logger.information(WStringMessage); //Did not compile because it only takes a String
        logger.information(StringMessage);
        system("PAUSE");
        return 0;
}
```

#### POCO version
1.8.1
#### Compiler and version
Microsoft Visual Studio 2017
#### Operating system and version
Windows 10

**Comment by obiltschnig** [comment]
std::wstring is not supported, mostly because it's a portability nightmare and only really used on Windows. You can use the Poco::UnicodeConverter class to convert from std::wstring to UTF-8 encoded std::string and use that for logging. The WindowsConsoleChannel will then convert UTF-8 back to UTF-16, so you can log Unicode characters on the console.

**Comment by obiltschnig** [comment]
You can use something like:

```c++
#include "Poco/UnicodeConverter.h"
// ...
std::string toUTF8(const std::wstring& utf16)
{
    std::string utf8;
    Poco::UnicodeConverter::convert(utf16, utf8);
    return utf8;
}
// ...
logger.information(toUTF8(StringMessage));
```
