### ISSUE TITLE
Multiple processes logging to the same log file - Poco::Logger

### ISSUE THREAD

**Issue by nangalvivek** [pocoproject/poco#2187]
I am using Poco(::Logger) for logging in my library. Since, multiple applications (using this library) can be running and write to the same log file.
I would like to know if this ( multiple processes logging to the same log file) is supported by Poco. I could not find anything related to this in the documentation.

**Comment by aleks-f** [comment]
There is nothing related in poco documentation because this is not a poco-related question. Poco will make sure that multiple threads (ie. threads within the same process) writing to the same file do not make a mess. When it comes to multiple processes, it depends what your operating system does there - most likely, you should make sure that concurrent writing to a single file from multiple processes is properly synchronized.

**Comment by Framnk** [comment]
On Windows it is not possible with the current POCO implementation because POCO opens the log file for exclusive write access.  So trying to create another POCO logger instance in another process will throw an exception.  So it is a POCO limitation in a way.

**Comment by aleks-f** [comment]
depends on the point of view; it  can also be considered a poco feature - to prevent an ungodly mess in a file meant to contain meaningful information.

**Comment by litterbug23** [comment]
most logger support multithread write/read the same log file at the same time.
why don't poco support  this feature?

**Comment by nangalvivek** [comment]
POCO does support writing to a log file from mutiple threads within the same process.
