### ISSUE TITLE
SQLite null pointer dereference occurs when exception is being thrown

### ISSUE THREAD

**Issue by jiajen** [pocoproject/poco#2277]
#### Expected behavior
A ConnectionFailedException should be thrown when the database fails to be created.

#### Actual behavior
A segmentation fault occurs due to a null pointer dereference occuring when the exception is being thrown.

#### Steps to reproduce the problem
The code below reproduces the problem:
```
try
{
	Poco::SQL::Session tmp(Poco::SQL::SQLite::Connector::KEY, "\\/some\\/invalid\\/path\\/sqlite.db", 1);
}
catch (Poco::SQL::ConnectionFailedException&)
{
}
```

#### Other relevant information
An attempt to throw an exception is made when the database fails to be created. However since the exception invokes a mutex, `sqlite3_db_mutex(pDB)` causes a segmentation fault when `pDB` is null which can occur if the database cannot be created. Fix included in #2276.

**Comment by DomXC** [comment]
The [Fix](https://github.com/pocoproject/poco/commit/27e7e532cc96ab353eb7d23f41d9bae561cd93f6) of #2278 fixes segmentation fault when pDB is null which can occur if the database cannot be created, however, causes wrong message is thrown - "Connection attempt failed: Can't open DB file: out of memory" is thrown instead of "Connection attempt failed: Can't open DB file".

To fix this, I would suggest to add guard to method [Utility::lastError](https://github.com/pocoproject/poco/blob/49aa90738ecf6837228f0de0a9d4fb0914a9e070/SQL/SQLite/src/Utility.cpp#L161) :


`	std::string errStr;
	SQLiteMutex m(pDB);
	if (pDB)
	{
		const char* pErr = sqlite3_errmsg(pDB);
		if (pErr) errStr = pErr;
	}
	return errStr;
`
