### ISSUE TITLE
Hash change for 1.9.0 release

### ISSUE THREAD

**Issue by woodruffw** [pocoproject/poco#2292]
Hi there,

I'm a maintainer with [Homebrew](https://github.com/Homebrew).

We've noticed (https://github.com/Homebrew/homebrew-core/issues/26606) that your latest release ([1.9.0](https://pocoproject.org/releases/poco-1.9.0/poco-1.9.0-all.tar.gz)) changed SHA256 checksums, from `028de410fc78d5f9b1ff400e93ec3d59b9e55a0cbbf0d8fec04636882b72ea45` to `0387bf0f9d313e2311742e1ad0b64e07f2f3e76039eed20e3b9aa9951b88e187`. 

To us, this indicates that someone has either modified your release (and is illicitly using your signing key) **or** that you've intentionally re-released a version.

Could a POCO maintainer confirm either of these?

Best,
William

P.S.: If this was an intentional re-release, *please* create a new version number in the future (and remove the old release entirely, if necessary) -- clobbering an existing version number causes all kinds of trouble for packager managers and maintainers, and confusion for the end users of your library who choose to install it via Homebrew.

**Comment by obiltschnig** [comment]
Package maintainers should use the packages at https://pocoproject.org/releases/ and verify with the provided [SHASUMS256.txt](https://pocoproject.org/releases/poco-1.9.0/SHASUMS256.txt).

Also, please wait until after the release announcement, as before "final" release, the files may change due to last-minute fixes.

I've heard about issues with GitHub packages changing checksums in the past, so please use the "official" packages.

**Comment by woodruffw** [comment]
> Package maintainers should use the packages at https://pocoproject.org/releases/ and verify with the provided SHASUMS256.txt.

> I've heard about issues with GitHub packages changing checksums in the past, so please use the "official" packages.

Yep, we pull from pocoproject.org, and not GitHub.

> Also, please wait until after the release announcement, as before "final" release, the files may change due to last-minute fixes.

I think this is where the problem is -- it's not clear when the release becomes "final". In this case, we [updated our checksum](https://github.com/Homebrew/homebrew-core/commit/f7b5fb3bed5d711764e80cd8693366903b54e70c.patch) after the [1.9.0 changelog was pushed](https://github.com/pocoproject/poco/commit/831fb72052e2d407dffa9f597569423210c0f811.patch).

In either case, we'll update the checksum now that we know the mismatch wasn't malicious.

**Comment by ilovezfs** [comment]
@obiltschnig the difference between the 028de410fc78d5f9b1ff400e93ec3d59b9e55a0cbbf0d8fec04636882b72ea45 tarball and the 0387bf0f9d313e2311742e1ad0b64e07f2f3e76039eed20e3b9aa9951b88e187 tarball is

```
Josephs-MacBook-Pro:poco joe$ diff old/poco-1.9.0-all/VERSION new/poco-1.9.0-all/VERSION 
1c1
< 1.9.0-all (2018-03-07)
---
> 1.9.0-all (2018-03-08)
```

That means you have allowed a release artifact to be published and then to be overwritten. Are you aware this is happening?

**Comment by obiltschnig** [comment]
Yes, because the release generation process has to be started locally. Timestamps match the official release announcements. I've probably run the release scripts the day before to test that everything works, and apparently those files got picked up. Will modify the workflow to publish pre-release test builds to a different directory to prevent this from happening.

**Comment by ilovezfs** [comment]
Thanks @obiltschnig!
