### ISSUE TITLE
Merge NetSSL_OpenSSL and NetSSL_Win

### ISSUE THREAD

**Issue by OgreTransporter** [pocoproject/poco#2328]
Hi,

I'm thinking about merging the two NetSSL packages for OpenSSL and Windows to one. My suggestion would be to use CMake to select a crypto provider (OpenSSL, Secure Channel/Windows) and then compile the code with corresponding flags. Best example is libcurl, where you can choose the TLS backend. Of course, the poco crypto library must first be adapted to work without OpenSSL. Another advantage is that the code can be modified to support more libraries (LibreSSL, NSS, PolarSSL, etc.) in the future. This might simplifies the management of dependencies.

Regards,
Transporter

**Comment by obiltschnig** [comment]
We already had something similar a few years back. Basically we had a common API library with "plug-ins" for different providers like OpenSSL, SChannel and MatrixSSL. However, over the years NetSSL has diverged significantly from that, so it would be best to start from scratch. Main issue is feature divergence between the different providers. NetSSL_Win is not on par with NetSSL_OpenSSL, mostly due to restrictions in SChannel. 

I'd strongly advise not merging both implementations into a single library. I'd like to see a common "frontend" library with various provider libraries that can be switched at compile or even run time.
