### ISSUE TITLE
StreamSocket hangs when using SocketStream without calling shutdownSend

### ISSUE THREAD

**Issue by KevDi** [pocoproject/poco#2384]
#### Expected behavior
I want to use the StreamSocket with an SocketStream to send different Messages to a Server and get the Answers.

#### Actual behavior
If i use the Code shown under Steps to reproduce the problem the program hangs on the `copyStream` Function. Inside that it hangs on the `read` function from the InputStream. The Code only works if i call `socket.shutdownSend()`. If I call that before the `copyStream` Function is called everything works. But I couldn't use the Socket again to send another Message to the Server.
Is there a way to use the StreamSocket without calling shutdownSend on the Socket?
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)
```
Poco::Net::SocketAddress socketAddress{ "10.50.1.89", 8888 };
Poco::Net::StreamSocket socket{ socketAddress };
Poco::Net::SocketStream str(socket);

str.write << "Message1";
str.flush();
std::stringstream ss;
Poco::StreamCopier::copyStream(str, ss);
``` 
This causes the Programm to hang on the `copyStream` Function call.

```
Poco::Net::SocketAddress socketAddress{ "10.50.1.89", 8888 };
Poco::Net::StreamSocket socket{ socketAddress };
Poco::Net::SocketStream str(socket);

str.write << "Message1";
str.flush();
socket.shutdownSend();
std::stringstream ss;
Poco::StreamCopier::copyStream(str, ss);
``` 
This Version gets me the Answer of the Server but i could not reuse the socket to send another Message because I had to close the Sending Part of it.
#### POCO version
1.9.0
#### Compiler and version
Visual Studio 2017
#### Operating system and version
Windows 10

**Comment by roccocorsi** [comment]
Thank you.  You helped me with hanging StreamCopier I was facing.  I was doing something less demanding, interacting with HTTP server, so send the request and get the response is all I need, so shutdownSend() solves my issue.

Seems for your case SocketStream is probably not the right thing to use.  Sorry I have no real help except that there is a stackoverflow posting that suggests using DialogSocket class.

https://stackoverflow.com/questions/15540448/poconet-library-hangs-on-output-of-poconetsocketstream/25280624

**Comment by bridgewaterrobbie** [comment]
I have also encountered this issue. A note in the header might be a decent intermediary step.

**Comment by davidcallen** [comment]
I have also encountered this issue when trying to send the contents of a file on the socket.  
I tried the workaround of adding a shutdownSend() before the call to copyStream().  It now only sends 1025 bytes in the copyStream, but I have much more to send (50k to 100k).  Without the workaround it would usually miss the last part of the file contents. 
My code is like this : 
`std::streamsize SocketUtils::sendFile(Poco::Net::StreamSocket& streamSocket, const std::string& fileNamePath)
{
		Poco::Net::SocketStream ostr(streamSocket);
		Poco::FileInputStream istr(fileNamePath, std::ios::binary);		
		return bytesCopied = Poco::StreamCopier::copyStreamUnbuffered(istr, ostr);
}
`
Note I get the issue using copyStreamUnbuffered() and copyStream().
Any help greatly appreciated. This issue has been driving my nuts for days.

**Comment by Mike-Altwy** [comment]
I have the same issue here, seems the bug is still there. I just upgraded to the latest release (1.13.3, because there was a fix for another bug I'd bumped into).
If I use StreamCopier, it will hang inside this function. If I use classic poll and read on the underlying socket, I retrieve all my data which is available to read.
I can't use the "workaround" of shutdowning the underlying socket because I keep sending and reading with this socket after that.

**Comment by davidcallen** [comment]
It may be worth checking POCO_NO_AUTOMATIC_LIB_INIT in [Net/include/Poco/Net/Net.h].  Possible issue with the underlying call to WSAStartup() function.  This was flagged up by Microsoft Application Verifier as a possible issue. 
I now define POCO_NO_AUTOMATIC_LIB_INIT in my Cmake build of poco using a command like :  
```
cmake .. -G "Visual Studio 16 2019" -A Win32 -DENABLE_CRYPTO=OFF -DPOCO_NO_AUTOMATIC_LIB_INIT=TRUE
```
I think this has helped me, but not 100% on that.

**Comment by obiltschnig** [comment]
There is nothing we can do about this in our implementation.

What happens is that `Poco::StreamCopier` will read from `Poco::SocketStream` until an EOF condition happens. With a `SocketStream`, the EOF only happens if the other side closes the socket or shuts down its send direction. Otherwise, it will simply block until more data comes along or the connection is shut down by the other side.

The reason why the call to `socket.shutdownSend();` helps in that particular case is that it signals the other side that no more data (requests) will be sent. Therefore, after sending the remaining response data, the other side shuts down its half of the connection too, thus signalling EOF to the `SocketStream`.
