### ISSUE TITLE
ODBC SELECT WITH USE THROW EXCEPTION

### ISSUE THREAD

**Issue by topkung1** [pocoproject/poco#2406]
SQL table structure is username as varchar(20)

```
std::string test("admin");
sess << "SELECT * FROM test WHERE username = ?", use(test), now;
```

**An error shown as **
```
SQLSTATE = 42000
Native Error Code = 402
[Microsoft][ODBC SQL Server Driver][SQL Server]The data types varchar and text are incompatible in the equal to operator
```

Could it be a POCO bug or my mistake?

**SQL PROFILER - it shows**
```
declare @p1 int
set @p1=NULL
exec sp_prepexec @p1 output,N'@P1 text',N'SELECT * FROM test WHERE username = @P1','admin'
select @p1
```

**It should be 'varchar' instead of 'text'**

#### POCO version
poco-1.9.0-all

#### Compiler and version
Visual Studio 2017 

#### Operating system and version
Windows 10 x64

#### Other relevant information
SQL SERVER 2017

**Comment by topkung1** [comment]
What I did and it worked was
File : Data\ODBC\src\Binder.cpp

goto line number : 135
and change SQL_LONGVARCHAR,  to SQL_VARCHAR

and recompile.

can someone tell me that was the actual solution?

**Comment by aleks-f** [comment]
> can someone tell me that was the actual solution?

In this particular case, obviously yes. Generally, probably not, because it likely breaks other back-ends or versions thereof - such are the joys of all noble attempts to unify access to diversely implemented systems.

One would have to try all the different back ends/versions to know which one requires which and then engage in discovering the back-end version behind the ODBC facade to do the right thing at binding time.

**Comment by topkung1** [comment]
I think, Nowadays, Most of the people don't usually use 'text' in any case

Correct me If I'm misunderstanding and how I could do this the right way

**Comment by aleks-f** [comment]
> Correct me If I'm misunderstanding and how I could do this the right way

You are reasoning from the currently SQLServer perspective, and you are right - 'text' has been obsoleted in new versions. However, ODBC is covering more than just SQLServer - there is Oracle, MySQL, PostgreSQL, Sybase, DB2, etc. 

It's been a while since I've spent time in that library, one would have to do a proper "inventory" of what's currently out there and make the right decision how to (a) detect the right type at runtime, or (b) have it hardcoded with least "damage".

**Comment by iquestor** [comment]
I also see this issue, will try the fix recommended by topkung1. I have seen similar problems when working with MySQL with TEXT type fields
