### ISSUE TITLE
Visual Studio Detected Memory Leak when using Poco::XML::Document

### ISSUE THREAD

**Issue by KevDi** [pocoproject/poco#2438]
#### Expected behavior
Creating XML Document did not leak memory
#### Actual behavior
Creating XML Document leak memory
#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

Create a simple Console Application with Visual Studio 2017
This is the Code of the main Method:
```
#include "pch.h"
#define _CRTDBG_MAP_ALLOC  //To detect memory leaks
#include <stdlib.h>  // To detect memory leaks
#include <crtdbg.h>  // To detect memory leaks
#include <iostream>
#include <Poco/DOM/Document.h>
#include <Poco/DOM/AutoPtr.h>
int main()
{
	Poco::AutoPtr<Poco::XML::Document> pDoc = new Poco::XML::Document;
        std::cout << "Hello World!\n";
	_CrtDumpMemoryLeaks(); // Dump Memory Leaks
	return 0;
}

```
This Dumps the following long list of Memory Leaks:
```
{1976} normal block at 0x0130C048, 8 bytes long.
 Data: <, /     > 2C 18 2F 01 00 00 00 00 
{1975} normal block at 0x0130C0F0, 8 bytes long.
 Data: <  /     > 10 18 2F 01 00 00 00 00 
{1974} normal block at 0x0130BD70, 8 bytes long.
 Data: <  /     > F4 17 2F 01 00 00 00 00 
{1973} normal block at 0x0130BE88, 8 bytes long.
 Data: <  /     > D4 17 2F 01 00 00 00 00 
{1972} normal block at 0x0130C0B8, 8 bytes long.
 Data: <  /     > B8 17 2F 01 00 00 00 00 

... i omitted the rest of the Dump because it will be very long. (Can post it if needed)

{171} normal block at 0x012D8AF0, 8 bytes long.
 Data: <L       > 4C 0B 89 0F 00 00 00 00 
Object dump complete.
``` 
#### POCO version
1.9.0
#### Compiler and version
Visual Studio 2017
#### Operating system and version
Windows 10

**Comment by aleks-f** [comment]
Well, you're painting with a too wide brush here; two points:

1) your `_CrtDumpMemoryLeaks()` call will dump anything that has been allocated since the program start but not freed, which is many things besides the `XML::Document`
2) you new the `XML::Document` in `AutoPtr`, then call `_CrtDumpMemoryLeaks()` before the `AutoPtr` was destructed (and memory freed)

To properly check for leaks, you have to:

1)  set checkpoints at the points in code between which you are checking, and
2) make sure `~AutoPtr()` is called

Like this:

```
int main()
{
	_CrtMemState _state[3] = {0};
	_CrtMemCheckpoint(&_state[0]);
	{
		Poco::AutoPtr<Poco::XML::Document> pDoc = new Poco::XML::Document;
	}
	_CrtMemCheckpoint(&_state[1]);
	if (_CrtMemDifference(&_state[2], &_state[0], &_state[1]))
		_CrtDumpMemoryLeaks(); // Dump Memory Leaks
	return 0;
}
```

Try that, and you'll see that there is no leaks.

**Comment by KevDi** [comment]
As i wrote in Stackoverflow this answer helped me alot. Thank you very much
