### ISSUE TITLE
Poco Util ServerApplication

### ISSUE THREAD

**Issue by chenhaifeng2016** [pocoproject/poco#2444]
#### Expected behavior
serverapplication.h

static SERVICE_STATUS        _serviceStatus; 
	static SERVICE_STATUS_HANDLE _serviceStatusHandle; 

not found SERVICE_STATUS         and SERVICE_STATUS_HANDLE 
How to deal with?

#### Steps to reproduce the problem
(please make this a [SSCCE](http://www.sscce.org/), if applicable and reasonable)

#### POCO version
1.9
#### Compiler and version
vs2015
#### Operating system and version
windows 10

**Comment by cngzhnp** [comment]
Those structures are defined in Windows header files AFAIK. So, are you sure that windows.h header file is detected by VS2015? Because, it might be that your Windows SDK version can be obsolete as 8.1, from your project properties in VS2015, change it as 10.x.y.z version because of your operating system is Win10

**Comment by chenhaifeng2016** [comment]
thank you very much
