### ISSUE TITLE
Feature Request: Windows UWP Support

### ISSUE THREAD

**Issue by nathan-fps** [pocoproject/poco#2544]
Hi Folks,

Is the Universal Windows Platform (ie. Windows Store) a supported platform? If not, is it a part of your feature roadmap? I didn't see any build instructions for this platform and a naive,

```shell
> mkdir cmake_build
> cd cmake_build
> cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION='10.0' ..
> cmake --builld .
```

doesn't seem to work. Support for this platform would be amazing if possible.

Best,
Nathan

**Comment by Bjoe** [comment]
I have not much clue about "Universal Windows Platform" or Windows it self, but from cmake :-)

What are you mean with: 
> didn't see any build instructions for this platform

Is cmake failing to configure the project or compile error or did `cmake --build .` "nothing"?

Can you "paste" the cmake output here?

I see here [Using Cmake to build Universal Windows App](https://stackoverflow.com/questions/40803170/cmake-uwp-using-cmake-to-build-universal-windows-app) they execute cmake with:
`CMake -G "Visual Studio 14 2015" -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10`
Means, without 64-bit support? version 10 instead of 10.0?

**Comment by Bjoe** [comment]
Ok, for the message compiler I can investigate to improve this. For the UWP support I must hand over to @aleks-f or @obiltschnig or some other contributors they have more knowledge about Windows. Sorry, stay tuned it may take some time....

**Comment by obiltschnig** [comment]
From what I know about UWP, a port will be quite complicated, because basically the entire platform abstraction layer needs to be redone. In addition, UWP APIs use asynchronous I/O (for files and network) and it seems iostreams are not supported (or at least weren't when I last checked a couple of years ago). So probably not going to happen soon, at least not from @aleks-f or myself, unless someone pays for the work.

**Comment by nathan-fps** [comment]
@obiltschnig Thanks for the update. Makes sense
