### ISSUE TITLE
[Poco::Net] HTTP Download file with progression

### ISSUE THREAD

**Issue by jano42** [pocoproject/poco#2813]
Hello 

I'm wondering how could I do to download a file through http and have a progress report ?

I'm working on OSS [Yadoms](https://github.com/Yadoms/yadoms) and we use Poco and boost (for multiplatform bhavior).
We have an utility class which let any part of our code download a file [FileDownloader.cpp](https://github.com/Yadoms/yadoms/blob/master/sources/shared/shared/web/FileDownloader.cpp).
At this time, we are using boost to download file with reporting progression. (it works)
But we plan to reduce usage of boost library (not easy to understand, particularly with boost::asio) , and we'are searching for a Poco alternative.

After a look at poco sources, I don't find an easy way to do it.

Please could you help us to find a way to it  ?

Regards

**Comment by obiltschnig** [comment]
You can get the total file size (hopefully) from the server's HTTP response.
Then you can simply count the number of bytes read from the response stream and relate against content size.

Rough outline:
```c++
HTTPClientSession session(host, port);
HTTPRequest request(HTTPRequest::HTTP_GET, path, HTTPMessage::HTTP_1_1);
HTTPResponse response;
session.sendRequest(request);
std::istream& rs = session.receiveResponse(response);
if (response.getStatus() == HTTPResponse::HTTP_OK)
{
	std::streamsize contentLength = response.getContentLength();
	std::streamsize totalRead = 0;
	char buffer[1024];
	while (rs.good())
	{
		rs.read(buffer, sizeof(buffer));
		std::streamsize read = rs.gcount();
		totalRead += read;
		if (contentLength != HTTPMessage::UNKNOWN_CONTENT_LENGTH && contentLength != 0)
		{
			double progress = 100.0*static_cast<double>(totalRead)/contentLength;
			// report progress
		}
		// process buffer
	}
}
```

**Comment by smartguy1196** [comment]
I second @obiltschnig's answer. To expand on that. I believe that POCO streams the response, which means that POCO technically has no idea what the ultimate length will be.

As he said, part of the response header is the content length, but that is just a number that's placed there. Technically, the server could provide the client with a false content length or not provide one at all, and still send the full response body. Most http clients will either break or catch this when the response finishes streaming, but that's not a guarantee. This is because HTTP is a protocol, not a promise--a protocol is a standard where both parties _assume_ that the other is complying and won't send back complete nonsense
