### ISSUE TITLE
Poco Logging in a DLL throws exception

### ISSUE THREAD

**Issue by TonyAntonucci** [pocoproject/poco#2860]
I am having an issue where when I use the POCO logging functions in a C++ DLL, they throw an exception. The identical code runs fine in an EXE. 

void OpenPocoLog(void)
{
   AutoPtr<FileChannel>       pFile(new FileChannel);
   pFile->setProperty("path", "MyLogFile");
   pFile->setProperty("rotation", "daily");
   pFile->setProperty("archive", "timestamp");
   pFile->setProperty("times", "local");
   pFile->setProperty("compress", "true");
   pFile->setProperty("purgeCount", "31");   // Keep a month's worth of logs

   AutoPtr<AsyncChannel>      pAsync(new AsyncChannel(pFile));

   AutoPtr<PatternFormatter>  pPatternFormatter(new PatternFormatter);
   pPatternFormatter->setProperty("pattern", "%Y-%m-%d %H:%M:%S.%i: %t");
   pPatternFormatter->setProperty("times", "local");

   AutoPtr<FormattingChannel> pFormattingChannel(new FormattingChannel(pPatternFormatter, pAsync));
   Logger::root().setChannel(pFormattingChannel);

   Logger::root().setChannel(pFormattingChannel);

   g.log.logger = &Logger::get("MYLOG");

   // Set the default Logging Level - The host can change this with HOSTCONFIG_SETTING
   #ifdef _DEBUG
   g.log.logger->setLevel(Poco::Message::PRIO_DEBUG);
   #else
   g.log.logger->setLevel(Poco::Message::PRIO_INFORMATION);
   #endif

   // Throws the exception on the following line
    g.log.logger->debug("Debug message!");
}

**Comment by aleks-f** [comment]
Perhaps mixing release/debug binaries?

**Comment by TonyAntonucci** [comment]
Project is compiled 32bit with /MT.
Linked with poco\lib\PocoFoundationmtd.lib

Any other ideas?

**Comment by obiltschnig** [comment]
Which exception is thrown?

**Comment by TonyAntonucci** [comment]
Not at my computer at the moment.
But I traced it down to the _name in the Message if I remember correctly. It’s a null pointer exception.

**Comment by TonyAntonucci** [comment]
I now have the code not throwing an exception, and I wrapped it in a try/catch to be sure.
And it runs without error. But I do NOT get a log file produced.

Do the AutoPtr's need to stay in "scope"?  -- If the logger setup is done in a function for example, they will go out of scope at the end of the function. In a DLL everything is in a function.

I have the reference to the logger in a structure where I keep globals:
       g.log.logger = &Logger::get("MYLOG");

Any idea what is going on?
This is driving me crazy!

**Comment by DigDyn** [comment]
More Info:

      g.logger->debug("Message 0");              // This executed fine
      g.logger->information("Message 1");     //  This throws an exception

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by obiltschnig** [comment]
It's very likely since you're linking the DLL statically that you have multiple copies of both the POCO libraries and the CRT in your executable. This also means multiple copies of POCO's static variables. This is something to avoid, and can explain the weird behavior you're seeing. If you are using POCO in both the main executable in the DLL, make sure you use the DLL CRT libraries and also link POCO as a DLL to both. Make sure that both the DLL and the main .EXE link the exact same DLL. Everything else is a recipe for troubles in my experience.

If only your DLL is using POCO and not your main executable, it could also be an initialization issue with the DLL - the POCO static objects may not be initialized properly.

**Comment by TonyAntonucci** [comment]
Hi Gunter,

Thank you for your reply. The main .EXE is actually in C#/.Net, so no Poco
there.

"  it could also be an initialization issue with the DLL - the POCO static
objects may not be initialized properly." --- How do I initialize the Poco
static objects? Is there some initialization calls?

By the way, I have been using Poco for a long time in this DLL. But I only
recently started using the Poco Logging. And I virtually cut-n-pasted the
code from your PDF slides on logging.

And to be clean when I said everything is working in the EXE, that is a
separate project. The EXE for the DLL that is having the problems (as I
said above) is a C#/.Net application.

Thanks!

*Tony*

**Comment by TonyAntonucci** [comment]
You mentioned "initialize the POCO static objects" above. 
How is that accomplished?

**Comment by aleks-f** [comment]
see if [this](https://stackoverflow.com/questions/5114683/loading-dll-not-initializing-static-c-classes) applies to your case. I doubt this is a Poco::Logger problem.

**Comment by DigDyn** [comment]
Hi Aleksandar,

It turned out to be a packing problem.
Structure packing was the root cause.
Was not a Poco issue.

*Tony Antonucci*
Digital Dynamics Software, Inc.
444 S. Rand Rd. - Suite 102-L
Lake Zurich, IL  60047
(847) 330-3830 - Office
(847) 619-3898 - Fax
(708) 542-3899 - Cell
(847) 380-1830 - Skype
