### ISSUE TITLE
error while building the project in "StreamSocket.h"

### ISSUE THREAD

**Issue by rohanvivek** [pocoproject/poco#2915]
after using the following command in the initial stage of building the project 

 "cmake --build . --config Release"

I'm getting an error saying
 
" /usr/local/include/Poco/Net/StreamSocket.h:186:3: error: expected identifier before numeric constant
   BUFFER_SIZE = 1024
   ^
/usr/local/include/Poco/Net/StreamSocket.h:186:3: error: expected ‘}’ before numeric constant
/usr/local/include/Poco/Net/StreamSocket.h:186:3: error: expected unqualified-id before numeric constant"

**Comment by KevDi** [comment]
did you download the source code? Or from where do you build it?

**Comment by rohanvivek** [comment]
> did you download the source code? Or from where do you build it?

Yes I downloaded clone it from GitHub and followed each step given.. I build it from after creating new folder cmake-build as given in step..

**Comment by KevDi** [comment]
Because it looks like your system uses the header files under /use... Which are the ones normally installed via a package managerVon meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Rohan Vivek <notifications@github.com>Datum: Di., 11. Feb. 2020, 17:46An: pocoproject/poco <poco@noreply.github.com>Cc: Kevin Dick <kevin.dick91@yahoo.de>, Comment <comment@noreply.github.com>Betreff: Re: [pocoproject/poco] error while building the project in "StreamSocket.h" (#2915)
did you download the source code? Or from where do you build it?

Yes I downloaded clone it from GitHub and followed each step given.. I build it from after creating new folder cmake-build as given in step..

**Comment by rohanvivek** [comment]
> Because it looks like your system uses the header files under /use... Which are the ones normally installed via a package managerVon meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Rohan Vivek <notifications@github.com>Datum: Di., 11. Feb. 2020, 17:46An: pocoproject/poco <poco@noreply.github.com>Cc: Kevin Dick <kevin.dick91@yahoo.de>, Comment <comment@noreply.github.com>Betreff: Re: [pocoproject/poco] error while building the project in "StreamSocket.h" (#2915) did you download the source code? Or from where do you build it? Yes I downloaded clone it from GitHub and followed each step given.. I build it from after creating new folder cmake-build as given in step.. —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

Yeah.. once I also thought that and removed from package manger and retried and got the same error as both the code were identical to each other.

**Comment by KevDi** [comment]
I just downloaded a fresh copy of the Poco Sources and build it successfully on my linux system.
From the error message you gave us it looks like there are Header Files from poco left. Because i don't think you try to build the poco sources out of the `/usr/local/include/` Folder structure. 
Maybe you have a previous version of Poco installed there. 
Thats why it brings up the error. So try to remove that old version and build the new one again and it should work.
If its a problem with version 1.10 the error Message should look like that:

`FolderWhereYouDownloadedPoco/Net/include/Poco/Net/StreamSocket.h:186:3 ....`

**Comment by rohanvivek** [comment]
I tried to build the new version and getting the same error 
"/home/shaktimaan/tekenlight/poco/Net/include/Poco/Net/StreamSocket.h:169:3: error: expected identifier before numeric constant
   BUFFER_SIZE = 1024
"

**Comment by rohanvivek** [comment]
Anyone there?

**Comment by obiltschnig** [comment]
Looks like you have some older Poco headers somewhere on your system that interfere with the build.
