### ISSUE TITLE
Windows linking Poco::DataMySQL with MySQL/MariaDB libs

### ISSUE THREAD

**Issue by brussens** [pocoproject/poco#2947]
Hello.
On Windows it is not possible to use MariaDB as a database since MariaDB uses the name `libmariadb.lib` instead of `libmysql.lib`.

When using `#pragma comment(lib, "libmariadb")`, the Poco is built without problems with MariaDB.

When using MySQL 5.6/5.7, it compiles success. But there is another problem.

Also when trying to link `Poco::DataMySQL` with my project you get an error:

> CMake Error at src/Test/CMakeLists.txt:9 (add_executable): Target "TestTarget" links to target "MySQL::client" but the target was not
> found. Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?

If you manually connect Poco::DataMySQL in Visual Studio, the library works perfectly with a database.

Poco version: 1.10.1
Cmake version: 3.16.2 
MariaDB version: 10.4/10.3
MySQL version: 5.7.22/5.6.40
Windows 10 PRO x64 with VS 2019 Community

P.S.: Sorry for bad English.

**Comment by aleks-f** [comment]
It seems like there's another config #ifdef in the cards - the one specifying whether to link with MySQL or MariaDB client library.

If you can do it and send a pull against the devel branch, it will speed up the resolution.

**Comment by brussens** [comment]
At this point, from the working solution, I have this solution in `Poco/Data/MySQL/MySQL.h`
```cpp
#ifndef MySQL_MySQL_INCLUDED
#define MySQL_MySQL_INCLUDED
...
#include <mysql.h> //include header from mariadb or mysql
...
//
// Automatically link Data library.
//
#if defined(_MSC_VER) && !defined(POCO_NO_AUTOMATIC_LIBS)
    #if !defined(MySQL_EXPORTS)
        #pragma comment(lib, "PocoDataMySQL" POCO_LIB_SUFFIX)
    #endif

    #ifdef LIBMARIADB // Check mariadb specified constant
        #pragma comment(lib, "libmariadb")
    #else
        #pragma comment(lib, "libmysql")
    #endif
#endif
...
#endif // MySQL_MySQL_INCLUDED
```
But unfortunately, I'm not a C++ professional, as I'm just learning. If this option really suits you, I will be glad to send you a PR.

**Comment by Bjoe** [comment]
When I understand this correct, the problem is here in [FindMySQL.cmake](https://github.com/pocoproject/poco/blob/f810bd0b4129b2330e4a23ccf4d304be6ba36583/cmake/FindMySQL.cmake#L64)
We should add as additional `NAMES` `mariadb` .... but I'm little bit confused, because "libmariadb.lib" sound like the library is "database" library .... we need only the library to connect to the "database". My assumption is that, it should be `mariadbclient`. See also for Unix: https://github.com/pocoproject/poco/blob/f810bd0b4129b2330e4a23ccf4d304be6ba36583/cmake/FindMySQL.cmake#L85
