### ISSUE TITLE
websocketserver example

### ISSUE THREAD

**Issue by danielstock** [pocoproject/poco#2981]
hi，
sorry to bother.

i read the sample of websocketserver https://github.com/pocoproject/poco/blob/master/Net/samples/WebSocketServer/src/WebSocketServer.cpp,
and i have some questions:

1. the main architecture of this program is HttpServer/RequestHandlerFactory/RequestHandler.
When the web socket connection is established,  will a corresponding thread be created, which contains the RequestHandler?

2. the max thread number is determined by what？ HttpServerParams->setMaxThreads()  or the default thread pool size.

thanks a lot.

**Comment by kblaschke** [comment]
Since no one bothered to provide you an answer yet, here you go:

1. You're right, WebSocket is a protocol that works on top of a HTTP connection. So, essentially, a client connects to a plain HTTP(S) server, then sends a simple request with the `Upgrade: websocket` header. The server will then acknowledge the upgrade if supported and allowed and from now on you can use the current request as a WebSocket. That's why it reuses Poco's `HTTPServer` structure, which will indeed create a new thread for each incoming connection. That also means if you have a server with hundreds or thousands of concurrent connections, you'll need an incredibly high number of threads. 
2. The number of available threads is determined by the thread pool you've assigned to the `HTTPServer` instance. If you did not assign a specific thread pool, then `HTTPServer` will use Poco's default `ThreadPool` instance, which has a default maximum capacity of 16 threads, which would then also be the maximum for the `HTTPServer` instance of no other instance uses the default pool.

### In Detail: Limitations of Poco's Implementation

The `HTTPServer` implementation provided by Poco is easy to use and saves you from some lower-level network programming details, as each request is just a `Poco::Runnable`. On the other hand, and that's - in my opinion -  a serious drawback, it won't allow you to effectively write a server that can handle a very high number of connections, as threads have a relatively big system overhead to create them and then do all the context switching. It also may run you into system limitations, as most Linux distros for example limit the amount of processes and threads a single user may run. Some older kernels may even have a hard limit for the number of concurrently created (not running!) threads.

So what's actually missing here is an alternative implementation that doesn't use one thread per client connection, but rather implement use `select()` on all sockets in a single thread and then read any data that becomes available into buffers and notify handlers/consumers about that, which may then decide to handle this in a separate thread. But as initially said, this requires more low-level programming and also much more discipline, as all operations in the thread that selects and reads from the sockets will be serialized and can become a bottleneck if there's a lot of time-consuming processing happening on that level.

Sadly, Poco's network classes aren't very flexible when it comes to replacing a part in the chain, in this case, the `TCPServer` implementation (and `TCPServerDispatcher`, which actually creates the threads). Implementing a single-threaded server that uses a `select()`-based dispatcher requires different programming idioms. For example, you could not directly use the existing `HTTPRequestHandler` class, as this would block all current connections until the current request is done, essentially serializing all requests. As `WebSocket` instances are currently created inside that handler and might potentially run for hours - probably mostly sitting idle - before being terminated/closed, this is certainly not a good idea.

The `WebSocket` class would actually not require any changes, since it already works on a relatively low level by just sending and receiving data frames, which is a fast operation. So as long as you manage to reimplement `Poco::Net::TCPServer` and the derived `Poco::Net::HTTPServer` classes and create all the `HTTPClientSession`, `HTTPServerRequest` etc. classes required to construct the WebSocket instance, you could get this to work.
