### ISSUE TITLE
Poco::Net - return value from close needs to be checked in SocketImpl

### ISSUE THREAD

**Issue by d3matt** [pocoproject/poco#2982]
If close returns with -1 and errno is set to EINTR, the socket is still in an open state and the poco API will leak an fd. The return value for close needs to be checked and close retried if errno is EINTR. I haven't proven it yet, but I'm pretty sure I'm running into this with Poco 1.9.4 on Centos 7.

**Comment by bas524** [comment]
@d3matt @obiltschnig 

**FYI**

close is a rather special case. Not only is it not restartable on Linux; when close returns with EINTR on Linux, it has actually already succeeded, and making another call to close will fail with EBADF in single-threaded processes and cause extremely dangerous file-descriptor races in multi-threaded processes.

> As of the published POSIX 2008, this behavior is permitted:

> _If close() is interrupted by a signal that is to be caught, it shall return -1 with errno set to [EINTR] and the state of fildes is unspecified._

This issue was raised with the Austin Group (as Issue [#529](http://austingroupbugs.net/view.php?id=529)) and it was resolved to revise the specification such that returning with EINTR means the file descriptor is still open; this is contrary to the current Linux behavior. If the file descriptor has already been closed at the time the signal is handled, the close function is now required to return with EINPROGRESS instead of EINTR. This can be fixed in userspace on Linux, and there is an open [glibc bug report, #14627](http://sourceware.org/bugzilla/show_bug.cgi?id=14627) for it, but as of this writing it has not received any response.

This issue also has serious implications for POSIX thread cancellation, the side effects of which are specified in terms of the side effects upon returning with EINTR. There is a related issue on the Austin Group tracker, Issue [#614](http://austingroupbugs.net/view.php?id=614).

[Source](https://stackoverflow.com/a/14431867/1157444)
