### ISSUE TITLE
Why did development stop in February 2020?

### ISSUE THREAD

**Issue by FastInvite2k2** [pocoproject/poco#3053]
Development suddenly stopped in February 2020. But why?

**Comment by obiltschnig** [comment]
Mostly because the core developers are currently busy working on projects that actually help pay bills. Work on Poco will commence when time and resources are available.

**Comment by FastInvite2k2** [comment]
More developers are needed then.

**Comment by obiltschnig** [comment]
Why? What about a project reaching a state of being good enough?

**Comment by obiltschnig** [comment]
Seriously, the project would need 1-2 full time developers. But without proper funding, that's not going to happen.

**Comment by FastInvite2k2** [comment]
Wow, you switch between two extremes in 5 minutes. ;-) 1 or 2 hobby contributers would be enough.

**Comment by obiltschnig** [comment]
Well, for my own use (and probably for lots of others) the current state is just certainly good enough. Of course there are plenty of features that could be added and there are certainly a few bugs that may affect some people. 
There will certainly be a new release hopefully before Fall. But with the current state I won't commit to any schedule.
A lot more could be done with having 1-2 professional developers working on it at least part-time, especially in terms of feature and release planning (and following a roadmap). As for hobby developers, IME that's just another headache in managing development.

**Comment by aleks-f** [comment]
@FastInvite2k2 one or two hobby developers are not obligated to do anything. We know, because we’ve see many more than two over the course of 15+ years. What they usually do is what they are inclined to do at a given point in time, and that typically results in one of two scenarios:
1. They add lots of code they feel is good and needed, but is not necessarily so
2. They add something useful, even a whole solid library sometimes, and then ride into the proverbial sunset, never to be seen again, leaving us to deal with the future bug reports and feature requests

So, yes - funding, a guidance body, and dedicated paid personnel is needed to make and keep POCO a well-maintained and developed framework for wide use. Until we have that, it will remain actively developed in a direction our paying customers need, because we need to put food on our tables. If the rest of the world finds some of that useful, good.

**Comment by obiltschnig** [comment]
⬆︎ Well said @aleks-f.
