### ISSUE TITLE
Won't compile with gcc 10.2.0

### ISSUE THREAD

**Issue by jimmysue** [pocoproject/poco#3236]
message prints:
```
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking for C++14 compiler
-- Checking for C++14 compiler - unavailable
CMake Error at CMakeLists.txt:46 (message):
  Compiler does not support C++14.

```

**Comment by obiltschnig** [comment]
Sounds more like a CMake issue to me?

**Comment by Bjoe** [comment]
@obiltschnig Yes I think so :-)

It's an issue in [check_for_cxx14_compiler](https://github.com/pocoproject/poco/blob/3fc3e5f5b8462f7666952b43381383a79b8b5d92/cmake/CXX1x.cmake#L46)

Before I will try to fix this, I would like to discuss or ask, what is the purpose of this `check_for_cxx14_compiler` ?
cmake has support to "verify" c++ compiler flags/features see https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html

I would like to use the cmake approach because they have better support for many more compilers and we have lesser to maintain even I cannot support for example  `SunPro: Oracle SolarisStudio` or `NVHPC: NVIDIA HPC compilers` :-)

**Comment by obiltschnig** [comment]
Don't know what's the purpose of `check_for_cxx14_compiler`. Maybe @bachp has some insights?

**Comment by bachp** [comment]
@obiltschnig I don't know, it was added by @aleks-f https://github.com/pocoproject/poco/commit/dea76c8e2e8d6dc07c071d395a99d9c6f1b744e2.

From what I can tell it tries to automatically detect if the compiler supports C++11 or C++14 and set some config flags accrodingly. Is this still needed?

**Comment by obiltschnig** [comment]
Very likely not needed anymore as we can safely take C++14 for granted now, I would assume.

**Comment by obiltschnig** [comment]
The issue seems to be related to `ccache`. CMake build works fine with GCC 10.3 on Ubuntu 21.04.

**Comment by JackBoosY** [comment]
Was this issue fixed?

**Comment by TheMaverickProgrammer** [comment]
No. It went ignored and closed proving bots are no substitute for human care.
