### ISSUE TITLE
Task::postNotification possible leak

### ISSUE THREAD

**Issue by micheleselea** [pocoproject/poco#3240]
When we call this function
`void postNotification(Notification* pNf)`
if the _pOwner is null you will end up in a memory leak because you usually call the method like
`postNotification(new Poco::TaskCustomNotification<some_class>(`

and moreover if you try to do this
```
Poco::TaskCustomNotification<some_class>::Ptr cNF = new Poco::TaskCustomNotification<some_class>(this);
postNotification(cNF );
```
you will endup with a double delete, because the `_pOwner->postNotification(pNf);` inside take ownership regardless if you have the ::Ptr outside.
Probably the `postNotification(Notification* pNf)` should be changed in `postNotification(Notification::Ptr pNf)`

**Comment by Shelbylouis** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: micheleselea ***@***.***>
Sent: Monday, April 12, 2021, 1:26 AM
To: pocoproject/poco
Cc: Subscribed
Subject: [pocoproject/poco] Poco::Task::postNotification possible leak TaskCustomNotification (#3240)


When we call this function
void postNotification(Notification* pNf)
if the _pOwner is null you will end up in a memory leak because you usually call the method like
postNotification(new Poco::TaskCustomNotification<some_class>(

and moreover if you try to do this

Poco::TaskCustomNotification<some_class>::Ptr cNF = new Poco::TaskCustomNotification<some_class>(this);
postNotification(cNF );


you will endup with a double delete, because the _pOwner->postNotification(pNf); inside take ownership regardless if you have the ::Ptr outside.
Probably the postNotification(Notification* pNf) should be changed in postNotification(Notification::Ptr pNf)

—

  *   You are receiving this because you are subscribed to this thread.

**Comment by aleks-f** [comment]
@micheleselea the first part I understand, and it is is fixed. 

The second part I do not understand - you pass in `AutoPtr`, which is eventually duplicated (and should be released by the notification handler); your `AutoPtr` is also released - the memory will be freed once.

I agree that the function argument should have been AutoPtr to start with, but that train is gone, and we should not break the existing code at this point.

**Comment by micheleselea** [comment]
Ok I have to check what was the problem because was 1 year ago, anyway I think my point was
"Probably the `postNotification(Notification* pNf)` should be changed in `postNotification(Notification::Ptr pNf)`"
What I think is that if you change the postNotification like that you should deal with the first and second problem because that way if you use `postNotification(new Poco::TaskCustomNotification<some_class>(` you are safe even if _pOwner is null, and if you use an AutoPtr outside it's safe anyway because you do not end up with a double delete, I think we are not changing the compatibility with older code.
Otherwise when you call `postNotification(autoPtr)` you have to absolutely remember to do `postNotification(autoPtr.duplicate())` and I think my memory it's like RAM :D
But I think that my code works now with that call so I think that could be ok just to fix the first problem, do what you think it's better
