### ISSUE TITLE
[regression] Poco::Zip::ZipArchive does not detect actual incorrect local file headers

### ISSUE THREAD

**Issue by townsend2010** [pocoproject/poco#3259]
I'm working on an application that uses Poco to unzip an archive.  In testing my code to ensure I catch exceptions thrown from `Poco::Zip::ZipArchive`, I'm deliberately hacking a zip file to change the local file header signature to be something else and using that to unzip. However, in `ZipArchive::parse()`, this is not detected and just skipped as part of the `ZipUtil::sync()` call that was introduced in 19b168516c.

**Comment by townsend2010** [comment]
As further proof that 19b168516ce6 caused this regression, if I remove https://github.com/pocoproject/poco/blob/3fc3e5f5b8462f7666952b43381383a79b8b5d92/Zip/src/ZipArchive.cpp#L110, then I do get the exception if I "corrupt" the header signature.

**Comment by matejk** [comment]
This issue has been fixed in the current codebase. The `ZipArchive::parse()` method now uses a `haveSynced` flag to ensure `ZipUtil::sync()` is only attempted once per location - if it fails again, an `IllegalStateException` is thrown. Additionally, commit 1ed938848 ("fix(Zip): Improve parsing of non-standard ZIP archives") added further improvements including data descriptor handling for all compression methods and duplicate filename handling. A `ZipArchive::checkConsistency()` method was also added to verify CRC-32 and uncompressed sizes match between local headers and central directory headers.
