### ISSUE TITLE
JSON DataType support for MySQL 

### ISSUE THREAD

**Issue by aditya2410** [pocoproject/poco#3481]
We have a table in our DB , which has a column with Datatype JSON for MySQL. I am not able to Query this particular column using Poco::DataMySQL library. 
Following exception is thrown "MySQL: [MySQL]: unknown field type"

Does Poco::DataMysql not support JSON Data type?
If yes , could you please suggest a workaround for this.

we are using this version of software:
https://github.com/pocoproject/poco/archive/refs/tags/poco-1.11.0-release.zip

Cheers!

**Comment by hmartinez82** [comment]
@aditya2410 @obiltschnig I'm working on that. I haven't put a PR yet because I want to write Unit Tests first, and  I need to get the Data/MySQL unit tests compiling and running first 😅

Question: Do we want to return it as a string? I'm asking that because I'm not sure we want to add a dependency to  Poco::JSON from Data::MySQL (unless you tell me that it already depends on it)

**Comment by obiltschnig** [comment]
Returning (and passing) JSON as a string would be okay for me.

**Comment by aditya2410** [comment]
JSON as string is fine for our use case. 

cheers!
