### ISSUE TITLE
Net::WebSocket Can't receive when using Poco::Buffer

### ISSUE THREAD

**Issue by simotin13** [pocoproject/poco#3497]
Hi, I'm trying to use Net::Websocket for Websocket client tool.
I found a strange implementation at receiveBytes,
<pre>
int receiveBytes(Poco::Buffer<char>& buffer, int flags = 0, const Poco::Timespan& span = 0);
</pre>

Here is an example, receive string data and get std::string object.
<pre>
Poco::Net::WebSocket *pWebSocket;
...
... initialize WebSocket
...
Poco::Buffer<char> buf(0);
int recvLen = pWebSocket->receiveBytes(buf);
std::string recvStr(buf.begin(), recvLen);
</pre>
This code works.
But if I changed Buffer size not 0, 1～, I must write code like

<pre>
Poco::Net::WebSocket *pWebSocket;
...
... initialize WebSocket
...
Poco::Buffer<char> buf(256);
int recvLen = pWebSocket->receiveBytes(buf);
string wsResp(buf.begin() + 256, recvLen);
</pre>

This code also works, but I think it's strange.(looks a work around code)
I found cause of this behavior is WebSocketImpl::receiveBytes.

I think WebSocketImpl::receiveBytes should be like this,
<pre>
int WebSocketImpl::receiveBytes(Poco::Buffer<char>& buffer, int, const Poco::Timespan&)
{
	char mask[4];
	bool useMask;
	_frameFlags = 0;
	int payloadLength = receiveHeader(mask, useMask);
	if (payloadLength <= 0)
		return payloadLength;
	buffer.resize(payloadLength);
	return receivePayload(buffer.begin(), payloadLength, mask, useMask);
}
</pre>

It seems unnecessary to add `oldSize` to `payloadLength` for buffer.resize, just resize by payloadLength and it works on my WebSocket client tool.

If this change has no probrem, I can create a pull request about this issue.

This behavior also mentioned
https://github.com/pocoproject/poco/issues/2821#issuecomment-992173959

#2821 is about Poco::Buffer, so I create this issue.

**Comment by andrewauclair** [comment]
To me (from a decent amount of experience dealing with reading TCP/IP from sockets), this is an intentional design decision. The receiveBytes function is appending the new data to the end of the buffer. This is necessary because you're dealing with a stream of data that can be split into arbitrary chunks of data (packets). Because it's a stream and being split, you might not have all the data you need for processing at once. This means you might have some data left from the last packet when reading the next one.

I'm not familiar with Poco::Buffer, I use something different at work and we build some wrappers on top of the Poco Sockets. But it does look like Poco::Buffer supports setting the capacity, so that would avoid unnecessary allocations.

**Comment by simotin13** [comment]
Thank you for your comment.
I know TCP is stream data, and what you are saying.
But I still feel it's strange that we need to allocate Poco::Buffer with size 0 when we call receiveBytes, or skip pre-allocated size to get received data.Maybe this behaiver is related to Poco::Buffer design. 

Anyway, I can receive websocket packets with Poco::Buffer, I'll close this issue once.
Thank you.
