### ISSUE TITLE
[linux] Why is Poco::XML linked to Poco::Zip target?

### ISSUE THREAD

**Issue by ShailishThakur** [pocoproject/poco#3524]
As per CMakeLists.txt of Zip, 
target_link_libraries(Zip PUBLIC Poco::Util Poco::XML)

Poco::XML is linked to Zip target.
Why is it done? What functionality of Poco::XML is Poco::Zip dependent on?
What happens is Poco::XML is not linked to Zip? What functionalities of Poco Zip will be impacted?
I want to build and deploy Poco Zip on linux x86 without building and linking Poco XML. Is that possible?

**Comment by townsend2010** [comment]
Yeah, I have wondered the same thing and even a step further, `Poco::Util` is also not needed either.

**Comment by townsend2010** [comment]
Ah, I see this has been fixed in `devel` at 5568c005bc.  So we just need it in a proper release then :wink:

**Comment by townsend2010** [comment]
Ok, this is strange.  #2929 is supposed to be in [poco-1.11.0](https://github.com/pocoproject/poco/blob/f81a38057f1d240fe7b7a069612776f788bc88ea/CHANGELOG#L23), but it is certainly not in the [code](https://github.com/pocoproject/poco/blob/f81a38057f1d240fe7b7a069612776f788bc88ea/Zip/CMakeLists.txt#L24).  I believe a cherry-pick was 
missed into the 1.11.0 branch. :slightly_frowning_face: 

It would be great if this could be fixed in a maintenance release or the next release at the very least.  Thanks!
