### ISSUE TITLE
MailMessage::read() chokes on "Content-disposition"

### ISSUE THREAD

**Issue by lewandowski-a-j-gmail-com** [pocoproject/poco#3650]
I noticed that Net::MailMessage::read(std::istream&) is unable to parse a multipart message that contains 
"Content-disposition:" section (as oposed to "Content-Disposition:" which is parsed correctly).

I'm not an expert on email-related RFCs, but 
1) one of the email web-clients that I use did send a message with the problematic capitalization
2) this message was parsed correctly by two different webmail clients that I use (including Google's one)
3) MailMessage::read() does not seem have problems when I change "Content-Type:" to "Content-type:"

 A small example illustraitng the problem is in the attachment. To see the unexpected [incorrect?] behavior, simply
change "Content-Disposition:" to "Content-disposition:" in the raw_message string literal at the beggining of main().
The resulting new raw message string (obtained through Net::MailMessage::write()) does not have the section with "Content-disposition:" at all.
 
[poco-email-parser_cpp.txt](https://github.com/pocoproject/poco/files/9009080/poco-email-parser_cpp.txt)

**Comment by aleks-f** [comment]
should be case insensitive, [RFC 2822](https://datatracker.ietf.org/doc/html/rfc2822#section-1.2.2) supersedes [RFC 822](https://datatracker.ietf.org/doc/html/rfc822)

**Comment by aleks-f** [comment]
I can't reproduce the problem; MailMessage is using `Poco::ListMap`, which is case-insensitive by default:
https://github.com/pocoproject/poco/blob/191cbdc97e1d9de023b8a65e0dc844911c06f6a8/Foundation/include/Poco/ListMap.h#L31

From what I'm reading your code does not work because it expects to get the same casing back, but that won't happen - read will properly accept `Content-type`, but you will get back `Content-Type`.

I did not run your code, just changed casing in a test:
https://github.com/pocoproject/poco/blob/191cbdc97e1d9de023b8a65e0dc844911c06f6a8/Net/testsuite/src/MailMessageTest.cpp#L368
 to make sure different casing is properly accepted:
https://github.com/pocoproject/poco/blob/191cbdc97e1d9de023b8a65e0dc844911c06f6a8/Net/testsuite/src/MailMessageTest.cpp#L382

**Comment by aleks-f** [comment]
ok, I can reproduce the problem using your code, so disregard previous comment. scheduling this for 1.13

**Comment by lewandowski-a-j-gmail-com** [comment]
Thanks for really fast reply.
Best wishes,Adrian

W dniu środa, 29 czerwca 2022 Aleksandar Fabijanic ***@***.***>
napisał(a):
