### ISSUE TITLE
Parse json into specified descendant class

### ISSUE THREAD

**Issue by vmato** [pocoproject/poco#3656]
Is it possible to parse json into specified descendant class?

```
std::string json = "{ \"name\" : \"Franky\" }"

class Person : Poco::JSON::Object {
// ...
}

Person p = ???(json);

```

I've seen handlers but didn't find any explicit way to override JSON::Object creation

**Comment by aleks-f** [comment]
You "override" `JSON::Object` creation by implementing your `PersonHandler::asVar()` to return a `Dynamic::Var` which can be converted to Person.

As things stand now, it is doable, but not in an optimal way because `ParseHandler::setValue()` is private and so the whole handler should be reimplemented. We'll make it protected for 1.13
