### ISSUE TITLE
Questions about `Thread`

### ISSUE THREAD

**Issue by JackyWoo** [pocoproject/poco#3659]
Poco is really a wonderful lib that I use it in my project. Thank you.

I have some questions about `Thread`.

1. Why `current` method return 0 when it is main thread, it will cause user confusion
2. Why `setName` method does not really set thread name.

Expecting your responses

**Comment by aleks-f** [comment]
1. because main thread is not a `Poco::Thread`
2. I'm not understanding the question
https://github.com/pocoproject/poco/blob/191cbdc97e1d9de023b8a65e0dc844911c06f6a8/Foundation/src/Thread.cpp#L211-L216

**Comment by JackyWoo** [comment]
@aleks-f thanks for reply. 

>Why setName method does not really set thread name.

For example use `pthread_set_name_np`, `prctl`.

In my case I want get thread name through `ps` command.

**Comment by aleks-f** [comment]
That can be added, you can send a pull. However, keep in mind that all `ThreadImpl`s must then have `setName` implemented (no-op implementations are ok, since we have the `_name` to fall back to. 

Here's a strange way to set it on Windows: https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2015/debugger/how-to-set-a-thread-name-in-native-code

**Comment by JackyWoo** [comment]
ok
