### ISSUE TITLE
Could NOT find MySQL (missing: MYSQL_INCLUDE_DIR)

### ISSUE THREAD

**Issue by DemKKK** [pocoproject/poco#3730]
In my computer I install [mysql8.0](https://github.com/mysql/mysql-server) from source code, and has set MYSQL_ROOT_DIR, but still does't work. I have notice that in FindMySQL.cmake file, poco find mysql as mysql/mysql.h after poco-1.10.1, but in mysql8.0 mysql.h installed in “inlcude” [dircetory,](https://github.com/mysql/mysql-server/blob/8.0/include/CMakeLists.txt#:~:text=SET(HEADERS,)) which means we could't  use mysql.h as <mysql/mysql.h>，so what should I do to solve this problem？it's same as this [issue](https://github.com/pocoproject/poco/issues/3445)
![image](https://user-images.githubusercontent.com/99391175/182510195-7c582725-6860-428e-9072-b0c99c7577f0.png)

**Comment by aleks-f** [comment]
You should fix it and send the fix as pull request to devel branch. Or wait until someone else does that.

**Comment by zosrothko** [comment]
@hmartinez82 @aleks-f @FreelancerCGN @DemKKK This last commit c023404a03668c179a0ee78a85093153313cb3b8 on the develbranch fixes the issue about Data/MySQL (include <mysql.h> not found. The real problem is coming from the CLang compiler that is looking for <mysql.h> into the system include diretories only when the include is in a ".h" file. When the #include <mysql.h> directory is in a *.cpp file, CLang is looking first in the local source directory. Then in Data/MySQL/scr, CLang found "MySQL.H" that is the wrong <mysql.h> include.

Look at the errors below

In file included from src/Utility.cpp:17:
In file included from include/Poco/Data/MySQL/Utility.h:21:
include/Poco/Data/MySQL/mysql.h:22:10: error: 'mysql.h' file not found with <angled> include; use "quotes" instead
#include <mysql.h>
         ^~~~~~~~~
         "mysql.h"
In file included from src/Utility.cpp:17:
include/Poco/Data/MySQL/Utility.h:23:10: error: 'mysql.h' file not found with <angled> include; use "quotes" instead
#include <mysql.h>
         ^~~~~~~~~
         "mysql.h"
src/Utility.cpp:18:10: fatal error: 'mysql.h' file not found
#include <mysql.h>
         ^~~~~~~~~
3 errors generated.

So the fix is consisting in removing all #include <mysql.h> from the Data/MySQL/src files and reference the <mysql.h> include only in Data/MySQL/include/Poco/Data/MySQL/MySQL.h
