### ISSUE TITLE
DNS.resolve() should not be sorted in HostEntry::removeDuplicates()

### ISSUE THREAD

**Issue by lingyphone** [pocoproject/poco#3807]
It is caused by commit https://github.com/pocoproject/poco/commit/8030564ff542bec3fadf72b3db2ba0169fe303cb#diff-b38b1a4ab2c3fa8c175cff4b6f7c55e7ce4cd720f423e0a2b91d88b8f472f3cc  

And it ruins the DNS round-robin or DNS load-balance

**Comment by matejk** [comment]
@lingyphone: is this issue still relevant?

**Comment by aleks-f** [comment]
@matejk yes, because of [this](https://github.com/pocoproject/poco/commit/8030564ff542bec3fadf72b3db2ba0169fe303cb#diff-b38b1a4ab2c3fa8c175cff4b6f7c55e7ce4cd720f423e0a2b91d88b8f472f3ccR82). we should find another way to get rid of duplicates (and hope nobody found a reason to rely on it being ordered by now)

**Comment by rtoelhoej** [comment]
@aleks-f, @matejk 
The sorting in removeDuplicates breaks DNS round-robin and DNS load-balance for our project as well.

We did tests and on Linux multiple IP's are returned with same value on Windows it doesn't return any duplicates.

A fix would be to change the removeDuplicates to remove without sorting, I think sorting was used because it's the easiest way to remove duplicates. (std::unique only checks next item in list, it doesn't check the whole list, so it requires the vector to be sorted.

Fix in Net\include\Poco\Net\HostEntry.h by updating removeDuplicates to use std::set/std::remove_if:

```
template <typename C>
void removeDuplicates(C& list)
{
	std::set<T> values;
	list.erase(std::remove_if(list.begin(), list.end(), [&](const T& value) { return !values.insert(value).second; }), list.end());
}
```
