### ISSUE TITLE
WebSocket::sendFrame(const void* buffer, int length, int flags) causes memory leak in congested network .

### ISSUE THREAD

**Issue by DeepShah31** [pocoproject/poco#3892]
Hi All,

Application: I have developed an application that uses WebSocket class API sendFrame() and this API calls continuously in the callback function (calls when new MJPEG frames come).

Issue: Please note I have used mtrace() to detect memory leaks, and I have put before-after sendFrame() API. my application's memory is increasing 50MB in just 10-15 min continuously.

This behavior occurs in the congested network only.

Poco library version: 1.11.1

**Comment by micheleselea** [comment]
That is quite strange because sendFrame calls WebSocketImpl::sendBytes that allocate a Poco::Buffer<char> that isautomatically deleted on end of scope. than it calls  StreamSocketImpl::sendBytes that calls SocketImpl::sendBytes that do the O.S. send.
So the only memory allocated from my point of view is in Poco::Buffer<char> but it's deallocated
