### ISSUE TITLE
POCO 1.12.4 always produces CryptoException when using OpenSSL3 without legacy module

### ISSUE THREAD

**Issue by andreya108** [pocoproject/poco#3936]
We are using the OpenSSL3 static library without legacy module, but the current POCO code does not suggest that this is a possible way to use it.

It always throws a CryptoException ("Could not load legacy OpenSSL provider") if it cannot load legacy module.

I'm guessing there must be some mechanism to avoid this behavior when a conscious decision not to use legacy module: some kind of automatic detection of the legacy module being unavailable, or some build config flags to completely disable legacy module in poco, or some initialization options at runtime to disable the use of legacy module.

**Comment by yuntong613** [comment]
same problems

**Comment by proffparadox** [comment]
I'm also encountering this issue on windows 11 with OpenSSL 3.0.8
I'm using msys2 for a package manager and the following OpenSSL Packages
https://packages.msys2.org/package/openssl?repo=msys&variant=x86_64

I'm using this package for Poco:
https://packages.msys2.org/package/mingw-w64-x86_64-poco

This is my current CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.22)
project(OpenFIRDS)

set(CMAKE_CXX_STANDARD 23)

add_subdirectory(dependencies\\quill)
find_package(OpenSSL REQUIRED)
find_package(Boost REQUIRED COMPONENTS date_time)
find_package(Poco REQUIRED COMPONENTS Foundation Net NetSSL)

add_executable(OpenFIRDS src/main.cpp)
target_link_libraries(OpenFIRDS PRIVATE
        OpenSSL::Crypto
        OpenSSL::SSL
        quill::quill
        Boost::boost
        Boost::date_time
        Poco::Foundation
        Poco::Net
        Poco::NetSSL
        )
```
Main.cpp throws the error on this line:
```
Context::Ptr ptrContext = new Context(Context::TLS_CLIENT_USE, "", "", "", Context::VERIFY_RELAXED, 9, true, "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
```

I've tried modifying my OpenSSL.cnf to activate the legacy provider and its displayed in the commandline when running the command `openssl list -providers`

I've also set the `OPENSSL_ROOT_DIR` to the mingw64 install location.

I'm not sure how to debug the issue further from here and googling around the issue doesn't return many meaningful answers. Except that this is mainly caused by the switch from OpenSSL 1 to 3.

**Comment by HenryHu** [comment]
It seems like that even if I comment out the line which throws the exception, programs using crypto functionalities of POCO can still work, as long as they don't use the legacy functionalities. Maybe we should not throw an exception here at all?

**Comment by obiltschnig** [comment]
#4077
