### ISSUE TITLE
Question about HTTPRequestHandler

### ISSUE THREAD

**Issue by KevDi** [pocoproject/poco#4100]
I have a short question about the HTTPRequestHandler. 
In the `handleRequest` Method, to send a response to the Caller i send the data via: 
```
auto& outStream = response.send();
outStream << "Message";
```
Is there a way to already send the response during the `handleRequest` Method or do i have to wait until the Method returns before the Message is send to the Caller?

I did the function like this:

```
void Endpoint::handleRequest(Poco::Net::HTTPServerRequest& request, Poco::Net::HTTPServerResponse& response) {

    // Do something
    auto& outStream = response.send();
    outStream << "Message";
    // Do other stuff
}
```

I also added a Sleep after the `outStream << "Message"` for testing Purpose and noticed that the caller side hangs until the sleep was over and the method was completed.

**Comment by micheleselea** [comment]
You should add response setContentLength() or setChunkedTransferEncoding(true) before send() call, otherwise you can have problem receving that data. because the message is "small" S.O. optimize socket not sending every byte but when some "amount" is reached. Otherwise socket is flushed when is closing stream (on exit). if you want to flush data before exit function just call outStream.flush(); nut usually you do not need because sending is the last thing you do
