### ISSUE TITLE
Poco::FileStream is always opened with std::ios::in | std::ios::out

### ISSUE THREAD

**Issue by obiltschnig** [pocoproject/poco#4170]
It's not possible to open a `Poco::FileStream` with `std::ios::in` flags only, as the constructor always applies `std::ios::in | std::ios::out`. This can be an issue when opening files that are not writable.

**Comment by Mike4Online** [comment]
I had some code that broke on Windows and macOS between Poco 1.12.5p2 and 1.13.3 which did the following:

```
Poco::FileStream myFileStream;
myFileStream.open(myOutputFilePath, std::ios::binary);
```

The above code throws a `Poco::FileNotFoundException` when attempting to create the file specified by `myOutputFilePath`.

The following code change corrects this for Poco 1.13.X:

`Poco::FileStream myFileStream(myOutputFilePath, std::ios::out);`

The changes to the openmode defaults and the failure of specifying `std::ios::binary` should be listed as one of the breaking changes in the Poco 1.13.0 release notes (among the other breaking changes).

The `FileStream` documentation still shows a constructor which defaults to an openmode of `std::ios::out | std::ios::in` --

[FileStream](https://docs.pocoproject.org/current/Poco.FileStream.html)(
    const std::string & path,
    std::ios::openmode mode = std::ios::out | std::ios::in
);

It seems this openmode default value is no longer this way since this issue (#4170) was resolved.  if that is the case the documentation for `FileStream` should be revised accordingly.

The Description in the `FileStream` documentation still says that binary mode is always enabled even if not specified.  I assume that still applies to `FileStream` in Poco 1.13.
