### ISSUE TITLE
[Feature Request] Poco::format does not recognize the `P` type

### ISSUE THREAD

**Issue by Smurf-IV** [pocoproject/poco#4196]
As per the standard types, `P` is supposed to dump a pointer address (As hex reference) into the string

https://www.tutorialspoint.com/c_standard_library/c_function_sprintf.htm

But `Poco::format` does not (in 1.12.4 anyway !)

**Comment by aleks-f** [comment]
send a pull request with a testcase if you want this in

**Comment by andrewauclair** [comment]
I think the only way this can possible work is forcing the user to cast to `void*`.

Format.cpp
```cpp
case 'p':
    str < std::hex << std::showbase << AnyCast<void*>(*itVal++);
    break;
```

Then the calling code would be:
```cpp
int value = 0;
Poco::format("%p", static_cast<void*>(&value));
```

I don't believe it's possible to remove the `static_cast` because of the way `Poco::Any` works. Even if it were possible, it would require extra machinery inside `Poco::Any` to work.

**Comment by aleks-f** [comment]
@andrewauclair typed pointers are accessible, see [testAnyPointer()](https://github.com/pocoproject/poco/blob/56e340c0d880da8d684fcd7de36d70193701fb0b/Foundation/testsuite/src/AnyTest.cpp#L345), some accessors/detection has been added for 1.14. But I have no need, time or desire to add this feature and it's just creating noise - people post things then disappear, so I decided to close it

**Comment by andrewauclair** [comment]
That sounds good to me. I've moved to using fmtlib myself.
