### ISSUE TITLE
Poco::FileInputStream broken in 1.12.5 and 1.11.8.

### ISSUE THREAD

**Issue by jbulow** [pocoproject/poco#4241]
See https://github.com/pocoproject/poco/commit/4244c3251fd679d8d0f3d8a257b0c2886eb774f5#r131403165

**Comment by obiltschnig** [comment]
This will be properly fixed in [1.13](https://github.com/pocoproject/poco/milestone/42).

The main issue is that the original implementation with `_defaultMode` is broken conceptually.
Poco::FileInputStream, Poco::FileOutputStream and Poco::FileStream should have their own 
`open()` methods with appropriate defaults.

There will be patch releases 1.11.8p1 and 1.13.5p1 with interim fixes to maintain binary compatibility.
