### ISSUE TITLE
Cross-module exception issue with pre-compiler define _HAS_EXCEPTIONS=0 used in an application

### ISSUE THREAD

**Issue by siren186** [pocoproject/poco#4668]
Hi @obiltschnig 

I encountered a very subtle issue. It is about `Poco::Exception` in `PocoFoundation64.dll`. In Visual Studio 2019/2022 **release_shared** x64.
It is **very hard to reproduce**. Due to the large amount of code, I can't paste it all here, so I’ve only extracted a small portion.
```cpp
// This is a small portion I extracted from a large amount of code.
int main() {
    std::uint64_t val = 0x1122334455667788;
    
    try {
    	throw Poco::Exception("error"); 
        // If I do not use Poco::XXXXXXException, everything works fine.
        // throw std::exception("error"); // It's OK !!!
    } catch (const Poco::Exception& e) {
    }
    
    std::cout << val; // Now the val is 0x1122334400000000 !!!
    // It's Very Strange !!! It lost low 32 bit.
    return 0;
}
```

It took me two days to find the real reason.
```cpp
auto m = sizeof(Poco::Exception);
auto n = sizeof(std::exception);

// m=72, n=24: In PocoFoundation64.dll
// m=64, n=16: In my EXE
```

It was all caused by **`_HAS_EXCEPTIONS=0`** in my EXE compile options. This macro will change the class size and implementation of std::exception.
```cpp
// By: _HAS_EXCEPTIONS=1 (default in visual studio)
// sizeof(std::exception) == 24
namespace std { 
    class exception {
    public:
        virtual ~exception() {}
    private:
        char const* _What;
        bool        _DoFree;
    }
}


// By: _HAS_EXCEPTIONS=0
// sizeof(std::exception) == 16
namespace std { 
    class exception {
    public:
        virtual ~exception() {}
    protected:
        const char* _Ptr;
    }
}
```

I think it's necessary to **add some tips in POCO documentation** to avoid users wasting unnecessary time on this issue.

----
See alse: https://github.com/nodejs/node-addon-api/issues/85

**Comment by aleks-f** [comment]
This is cmake build system problem. VS projects have `/EHsc`

**Comment by matejk** [comment]
> This is cmake build system problem. VS projects have `/EHsc`

CMake adds /EHsc bz default when building on Windows:

`C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\HostX64\x86\cl.exe  /nologo /TP -DFoundation_EXPORTS -DPOCO_ENABLE_CPP11 -DPOCO_ENABLE_CPP14 -DPOCO_OS_FAMILY_WINDOWS -DUNICODE -DUTF8PROC_STATIC -D_DEBUG -D_UNICODE -IC:\github\build-poco-Desktop_Qt_5_15_2_MSVC2019_32bit-Debug\Foundation -IC:\github\poco\Foundation\include -IC:\github\poco\Foundation\src /DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /Zi /Ob0 /Od /RTC1 -std:c++17 -MDd /showIncludes /FoFoundation\CMakeFiles\Foundation.dir\src\ByteOrder.cpp.obj /FdFoundation\CMakeFiles\Foundation.dir\ /FS -c C:\github\poco\Foundation\src\ByteOrder.cpp
`
The problem is caused by defining `_HAS_EXCEPTIONS=0` in the application that is using Poco. The size of `std::exception` and `Poco::Exception` inside Poco binaries is correct.

Additional define in the application is the root of the problems, not the way Poco is built.

**Comment by matejk** [comment]
What can be done in Poco is to verify the value of `_HAS_EXCEPTIONS` in Poco header files and abort compile if it is set to 0.
