### ISSUE TITLE
BaseEncoderBuf line breaks and padding

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#712]
Base64EncoderBuf has [hardcoded line breaks](https://github.com/pocoproject/poco/blob/develop/Foundation/src/Base64Encoder.cpp#L39) at 72 characters; there is Base64EncoderBuf::setLineLength(int) but no way to access it from the encoder. Why 72 and shouldn't there be access to the feature from the encoder? Should there also be the same feature in 32-bit encoder?

OTOH, Base32EncoderBuf has [padding flag](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Base32Encoder.h#L54), while 64-bit does not.

So, the question is: keep both and align 32 and 64-bit versions or get rid of both of them?

@obiltschnig ?

EDIT: not directly related, but another annoying/confusing feature is that std::flush does not flush; if close() is not called on encoder, characters are missing. I understand "==" padding has to be done on close() only but shouldn't std::flush push all the contents into the enclosed stream?

**Comment by obiltschnig** [comment]
Given a Base64Encoder object, you can query/set the line length with encoder.rdbuf()->getLineLength()/setLineLength(). MIME limits the line length to 76 characters, therefore the default line length. Regarding flush: Since Base64Encoder does not use a buffer, except for the current group of 3 characters, flush does not make sense. You cannot write anything until a group of three characters is complete, or you're done and call close, in which case the last incomplete group can be properly padded.

Furthermore, 32-bit and 64-bit versions should have the same interface. I didn't write the Base32Encoder class, but I'm strongly for consistent interfaces.

**Comment by aleks-f** [comment]
OK, all clear except how exactly to align the interfaces; add line break length to 32-bit and padding to 64-bit? Or remove padding flag from 32-bit?

**Comment by obiltschnig** [comment]
Remove padding flag and make line length configurable.
Just in case keep padding flag in ctor and set line length accordingly.

--
G�nter Obiltschnig
Applied Informatics Software Engineering GmbH
A-9182 Maria Elend | Maria Elend 143 | www.appinf.com
P: +43 4253 32596  M: +43 676 5166737

Company Registration: FN 276491 f | Landesgericht Klagenfurt
Managing Director: DI G�nter Obiltschnig
