### ISSUE TITLE
ServerApplication close console

### ISSUE THREAD

**Issue by jano42** [pocoproject/poco#746]
The issue is reproduced in Windows environnement

I've cerated a ServerApplication. 
The aim is to run either as a service or directly from a console.

![2015-03-15 09_44_54-yadoms - microsoft visual studio](https://cloud.githubusercontent.com/assets/3135683/6655272/2d4d2a8e-caf8-11e4-9090-45d383ee9c60.jpg)

If I run the application in a console, then terminate it with "Ctrl+C" all is OK.
If I run the application in a console, then terminate it by **closing the window then  neither my last lines are not called, nor uninitialize overidden uninitialize method**.

I've reproduced the same behavior with the Sample/ServerApplication

**Comment by aleks-f** [comment]
There is no substantial difference between Ctrl-C and closing the window because handler is [the same](https://github.com/pocoproject/poco/blob/39b6c79e46e60530291f4f455883a4caec11944f/Util/src/ServerApplication.cpp#L125). Your code image is useless in two ways:

- it does not show any relevant code (e.g. what is CSupervisor doing, especially when you call requestToStop()?, how do you know unitialize is not called, is there a log?); note that I am [not](http://sscce.org/) calling here for a wholesale dump of your entire application code

- it is an image; what's wrong with [markdown](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting)?

**Comment by jano42** [comment]
I agree with you, with handler is the same between Ctrl+C and closing window; but behavior is not !

It is easy to reproduce. 

I've opened the "Util\samples\SampleServer" sample.

I just add log lines (step 2 to 4) to highligth the bug.

~~~
	int main(const ArgVec& args)
	{
		if (!_helpRequested)
		{
			TaskManager tm;
			tm.start(new SampleTask);
			waitForTerminationRequest();
            logger().information("STEP 2"); 
			tm.cancelAll();
            logger().information("STEP 3");
            tm.joinAll();
		}
        logger().information("STEP 4");
        return Application::EXIT_OK;
	}
~~~

The result:
==========

Here are the log files (given with using SampleServer.properties : provided with poco)

Ending by Ctrl+C
---------------

~~~~
Application: [Information] starting up
Application: [Information] busy doing nothing... 0d 00:00:05.087
Application: [Information] busy doing nothing... 0d 00:00:10.108
Application: [Information] STEP 2
Application: [Information] STEP 3
Application: [Information] STEP 4
Application: [Information] shutting down
~~~~

Ending by closing Window
----------------


~~~~
Application: [Information] starting up
Application: [Information] busy doing nothing... 0d 00:00:05.046
Application: [Information] busy doing nothing... 0d 00:00:10.068
~~~~

Neither the Step2 to 4 are called, nor  the uninitialize overriding method 

~~~
	void uninitialize()
	{
		logger().information("shutting down");
		ServerApplication::uninitialize();
	}
~~~

Using poco-1.6.0 complete edition, with Windows 7 64bits and VisualStudio 2013

Sorry for my poor markdown knowledge.
