### ISSUE TITLE
Meaning of _used member in Poco::Buffer

### ISSUE THREAD

**Issue by DBarzo** [pocoproject/poco#760]
Hi,

If I have not misunderstood, the _used member in Poco::Buffer should contains the number of 'valid' data into the buffer.
But, if so, I have some doubts. 
In some situation, it has the same meaning of 'capacity'...

For example, in the constructor:

    Poco::Buffer<UINT8> _buffer(100); // _used is initialized to 100
    bool is_empty = _buffer.empty();  // Return FALSE!

or using the clear() method:

    Poco::Buffer<UINT8> _buffer(100);
    _buffer.append(_data);
    _buffer.clear();   // _used is not cleared
    bool is_empty = _buffer.empty();  // Return FALSE!

Is this the desired behavior?

Of course I could have a buffer with all "valid" '0' but, in this case I will use the ctor:

    Buffer(T* pMem, std::size_t length)

where _used is correctly valorized.

Daniele.

**Comment by aleks-f** [comment]
When [empty()](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Buffer.h#L298) is true, it means the size of used data in buffer is zero. _used is the valid (used) size, see [Buffer::size()](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Buffer.h#L262). Calling [clear()](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Buffer.h#L256) zeroes the used memory but does not empty the buffer. There may be a difference between used and capacity because, after the buffer is shrunk to smaller capacity, unused memory is not deallocated, see [resize()](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Buffer.h#L117) and [setCapacity()](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Buffer.h#L145)

**Comment by DBarzo** [comment]
Hi Alex,
thanks for the reply.
I change my code from **my_buffer.clear()** to **my_buffer.resize(0)** to 'destroy' (or 'invalidate') the buffer, I don't have found another way to do it :smile:
