### ISSUE TITLE
Using Poco to send email without authentication

### ISSUE THREAD

**Issue by Cupidvogel** [pocoproject/poco#771]
A few days back, I raised a question- https://github.com/pocoproject/poco/issues/768 on how to send email with secure authentication via Poco. The final solution worked. 

Is it possible to send email without the auth part? That is, I will just mention the sender's email address (say {user-id}@amazon.com [my corporate Amazon Exchange mail account]), the receiver's address, the attachments and content? I want to skip the smtp server name, username, password (I can provide a port if necessary, but guess it is not needed in absence of host name).

If so, can anyone guide me how? Almost all examples I have come across don't work, the one in the issue I raised worked after multiple iterations, that's why I am asking.

**Comment by Cupidvogel** [comment]
Any guidance, any one?

**Comment by bakercp** [comment]
I've not heard of something like this. How do you do it normally outside of Poco?

**Comment by Cupidvogel** [comment]
Neither have I. But there is a mail API in Java - JavaMail, which lets user send emails from completely nonexistent email addresses and it is still delivered to where it was meant to. My colleague used it and sent an email from some cock and bull address like <his_name>@<his_name123abc>.com to his personal email id, and it was delivered correctly. So it looks like there is some way, even though I don't know honestly how that works...

**Comment by bakercp** [comment]
Open SMTP servers (not many of these left because they were used for spam) can send any message. They don't check validity of the address. You could do this on the command line of most Unix systems. Basically, you would use poco SMTP with an open SMTP server which could be your own. That said, most popular mail providers will be able to recognize the mismatch between the from field and the originating server and flag it as spam.

**Comment by Cupidvogel** [comment]
Assuming that it is our organization email address to which those emails are sent, and we have somehow instructed it to not treat emails from this {fake_id}@{fake_host}.com address as spam. How do I configure Poco (vis-a-vis the working code in Issue#768) to be able to send it?

**Comment by bakercp** [comment]
Can you share the code you wrote that is failing?

**Comment by Cupidvogel** [comment]
I didn't write any code at all. This the one which was working, as explained in Issue#768 -

```
#include <iostream>

#include "Poco/Net/MailMessage.h"
#include "Poco/Net/MailRecipient.h"
#include "Poco/Net/SMTPClientSession.h"
#include "Poco/Net/NetException.h"
#include "Poco/Net/SecureSMTPClientSession.h"
#include "Poco/Net/InvalidCertificateHandler.h"
#include "Poco/Net/AcceptCertificateHandler.h"
#include "Poco/Net/SSLManager.h"
#include "Poco/Net/SecureStreamSocket.h"
#include "Poco/Net/MailRecipient.h"

using Poco::Net::InvalidCertificateHandler;
using Poco::Net::AcceptCertificateHandler;
using Poco::Net::Context;
using Poco::Net::SSLManager;
using Poco::Net::SecureStreamSocket;
using Poco::Net::SocketAddress;
using Poco::Net::SecureSMTPClientSession;
using Poco::Net::SMTPClientSession;
using Poco::SharedPtr;
using Poco::Net::MailMessage;
using Poco::Net::MailRecipient;
using namespace std;


int main(int argc, char** argv)
{
  string host = "smtp.gmail.com";
  int port = 465;
  std::string sUserName = "my_email_id";
  std::string sPassword = "my_password";
  std::string to = "recipient";
  std::string from = "my_email_id";
  std::string subject = "Your first e-mail message sent using Poco Libraries";
  std::string content = "Well done! You've successfully sent your first message using Poco SMTPClientSession";
  MailMessage message;

  try {
    SharedPtr<InvalidCertificateHandler> pCert = new AcceptCertificateHandler(false);
    Context::Ptr pContext = new Poco::Net::Context(Context::CLIENT_USE, "", "", "", Context::VERIFY_NONE, 9, false, "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
    SSLManager::instance().initializeClient(0, pCert, pContext);

    SecureStreamSocket pSSLSocket(pContext);
    pSSLSocket.connect(SocketAddress(host, port));
    SecureSMTPClientSession secure(pSSLSocket);

    secure.login();
    bool tlsStarted = secure.startTLS(pContext);
    secure.login(SMTPClientSession::AUTH_LOGIN, sUserName, sPassword);

    message.setSender(from);
    message.addRecipient(MailRecipient(MailRecipient::PRIMARY_RECIPIENT, to));
    message.setSubject(subject);
    message.setContentType("text/plain; charset=UTF-8");
    message.setContent(content, MailMessage::ENCODING_8BIT);

    secure.sendMessage(message);
    secure.close();

  } catch (Poco::Net::SMTPException &e) {
    cout << e.code() << endl;
    cout << e.message() << endl;
    cout << e.what() << endl;
    cout << e.displayText().c_str() << endl;
  }
  catch (Poco::Net::NetException &e) {
    cout << e.code() << endl;
    cout << e.message() << endl;
    cout << e.what() << endl;
    cout << e.displayText().c_str() << endl;
  }

  return 0;
}
```

I tried this with my gmail id as username and from address, smtp.gmail.com as host, 465 as port, and my actual password, and it worked fine. Now I want it to work with any email id (even non-existent), thus obviating the need to give any host, port, username or password.  So I could not figure out what to do.

**Comment by aleks-f** [comment]
You should query DNS for MX records. That will give you SMTP servers. Port you know already, use default. Whether server will relay without credentials depends on the server implementation/configuration.

**Comment by Cupidvogel** [comment]
Query DNS for MX records meaning?

**Comment by bakercp** [comment]
Query domain name system server (https://en.wikipedia.org/wiki/Domain_Name_System) for mail exchanger records (aka MX record) (https://en.wikipedia.org/wiki/MX_record).

Also, to communicate with an SMTP (https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol) server, you'll usually need a host and port, though you might not need a username and password.

For insecure servers, you won't call `SecureSMTPClientSession::login`.  In fact, you might not need an SSL secured session and could just use `SMTPClientSession` for old-fashioned SMTP on port 25.

**Comment by Cupidvogel** [comment]
Okay. Will do.

**Comment by Cupidvogel** [comment]
What exactly should I query for? I tried http://mxtoolbox.com/SuperTool.aspx, and gave simple examples like smtp.gmail.com, and it returned some results along with the IP address.

**Comment by bakercp** [comment]
So - do you understand how the SMTP protocol works?  It seems a little background reading would be in order https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol  I think some test code that you write after a thorough study of the protocol will make this conversation more productive. 

Querying for MX records is a way to find a mail exchange server to send mail to or for finding smtp servers.

**Comment by Cupidvogel** [comment]
Nuh, I never really understood how it works. Okay, will take some time to study it and get back to this discussion..

**Comment by bakercp** [comment]
:+1:

**Comment by Cupidvogel** [comment]
Sorry guys for being late. I did some background study, and have a basic understanding of the email workflow. I verified with Java Mail and another mailing library SendGrid, both of which allow users to send email from non-exisiting email addresses. In these cases, like you said, the library itself behaves as a SMTP server. We are fine with that, we can set a filter on our company mailing service to not treat mails from this address as spam.

Now how do I it in Poco? I found what MX records are, they are DNS records that map email addresses to the corresponding mail servers so that mail can be relayed by SMTP to those mail servers.

Why do I need to search MX records in this case? What am I searching for?

**Comment by Cupidvogel** [comment]
Can anyone help?

**Comment by aleks-f** [comment]
If you asked more meaningful questions, maybe someone would help. 

You said:
> I want to skip the smtp server name, 

Now you ask:
> Why do I need to search MX records in this case?

You can't skip SMTP server name. You can only automate it's discovery by querying amazon.com for it's MX records.

> there is a mail API in Java - JavaMail, which lets user send emails from completely nonexistent email addresses and it is still delivered to where it was meant to. 

Whether you will be required to provide username/password and send from fake email depends on the SMTP server.

**Comment by Cupidvogel** [comment]
Yes, that's what I said before. Then I looked up and found how Java Mail or Send Grid works, and in my last reply asked whether Poco can behave in the same way, that is, with a built in SMTP server that allows specifying a non-existent sender email address. So I want to know whether Poco can do the same, and if so, how.

**Comment by aleks-f** [comment]
No, there is no built-in SMTP server in Poco.

**Comment by Cupidvogel** [comment]
Thanks. So I queried for amazon.com, and I found a number of SMTP servers. One such is amazon-smtp.amazon.com with IP address 207.171.178.25..Is it possible to specify this (like I have been doing smtp.gmail.com for Gmail) as the smtp server? If so, how do I make it non-secure, so that it doesn't have to come with any username/password requirement?

**Comment by bakercp** [comment]
Have you tried using the `smtp.amazon.com` server to send your mail without credentials (i.e. http://pocoproject.org/docs/Poco.Net.SMTPClientSession.html#24053 `.login("smtp.amazon.com")`  I doubt, very strongly, that they will not require authentication.  Otherwise, every spammer in the world would be sending their spam mail through Amazon's servers.  As was the case three weeks ago, I still feel like you need to do a bit of background research to better understand the differences between and smtp clients, smtp relays / server, mail exchanges, etc.  The bottom line is that due to the proliferation of spam, very few mail relays (like smtp.amazon.com) will allow anyone to connect without credentials and send any mail they want through their servers.  Of course anyone can turn their computer into an smtp relay or send mail directly without a mail relay (http://www.simplehelp.net/2008/12/01/how-to-send-email-from-the-linux-command-line/).  But email services like gmail will quickly send unauthenticated mail to the spam folder (or reject it outright from untrusted sending ips / servers).

**Comment by Cupidvogel** [comment]
Thanks. I have tried that, and the mail is not sent. And as for my knowledge, yes, it still is lacking. I tried studying some books on Postfix on how the entire process works, but got bogged down mid way.

**Comment by obiltschnig** [comment]
To send an email without an intermediate SMTP server (the server you usually specify in your email client as server for outgoing email), you'll have to deliver the email directly to the receiver's SMTP server. To find out the receiver's SMTP server for a given email address, you use the DNS system and query MX records. For example, if you want to send an email to user@example.com, you'll have to look up the MX record for example.com. As a fallback, if there is no MX record for a domain name, use the normal address record for that domain. Once you have the IP address of the destination SMTP server (from the MX record), pass this to Poco::Net::SMTPClientSession and send the email. You won't have to authenticate against this server.

HOWEVER:
Querying MX records cannot be done with POCO, so you'll have to use some other library, or implement this yourself.
Also, the target server is very likely to reject your email as spam (e.g., due to a failed PTR/reverse DNS check and other anti-spam measures).

THEREFORE:
If you want to send an email from your application, and you care about those emails being delivered, always do this using a proper user-configurable outgoing SMTP server.

**Comment by Cupidvogel** [comment]
Thanks. Got it. We will be using an emailing service like SendGrid probably. It works fine.
