### ISSUE TITLE
Enable C++11 through CMake on OSX

### ISSUE THREAD

**Issue by aaboyd** [pocoproject/poco#826]
This relates to 
[#234](https://github.com/pocoproject/poco/issues/234) and [#657](https://github.com/pocoproject/poco/issues/657)

Seems like there was an addition to the compiler flags for Darwin-clang-libc++ so that C++11 was enabled.  I ran into the issue mentioned in 657, is there any convenient way to run cmake on Mac OS X and have C++11 turned on?

If not, any ideas where or how to add this?
Should it be an FORCE_C++11 option in the CMakeLists.txt file?

**Comment by aleks-f** [comment]
This has to do with XCode command line tools location. I was able to reproduce it and fix it (for both, with -std=c++11 and without it) by following instructions in [this post](http://stackoverflow.com/questions/26185978/os-x-mavericks-wchar-h-file-not-found)

**Comment by aaboyd** [comment]
I can build with ```make``` and with ```cmake```, the problem is that when you build the poco libraries using the cmake build there is no convenient way to add flags without modifying the ```CMakeLists.txt``` directly.

I have a script that runs cmake.

```
cmake "${POCO_ROOT}" "-G" "Xcode"\
	"-B${POCO_BUILD_DIR}"
```

Relevant output of above command.
```
-- C_FLAGS:  =
-- CMAKE_C_FLAGS_DEBUG:=-g
-- CMAKE_C_FLAGS_RELEASE:=-O3 -DNDEBUG
-- CMAKE_C_FLAGS_MINSIZEREL:=-Os -DNDEBUG
-- CMAKE_C_FLAGS_RELWITHDEBINFO:=-O2 -g -DNDEBUG
-- 
-- 
-- CXX_FLAGS:=
-- CMAKE_CXX_FLAGS_DEBUG:=-g
-- CMAKE_CXX_FLAGS_RELEASE:=-O3 -DNDEBUG
-- CMAKE_CXX_FLAGS_MINSIZEREL:=-Os -DNDEBUG
-- CMAKE_CXX_FLAGS_RELWITHDEBINFO:=-O2 -g -DNDEBUG
```  

I'm trying to use ```-std=c++``` and ```-stdlib=libc++``` in my project, so I want to be able to compile Poco with those flags.   If you don't actually put those flags in everything will compile and link correctly, but you run into some odd runtime errors if you link a non-libc++ library with a libc++ library.  With ```./configure``` and ```make``` you have the option to define the ```--config=Darwin-clang-libc++```, but I don't see any easy way to do that with Poco without modifying the project files.

**Comment by aleks-f** [comment]
Ah, that. Yes, it's a problem. We should separate C and C++ flags. Right now, there is --cflags; I tried it with Darwin-clang config, but the flags are applied indiscriminately and clang bombs when it encounters a *.c file. So, currently the best quick solution for your problem is to create Darwin-clang-libc++98

**Comment by aaboyd** [comment]
I'm doing a poor job of articulating this, sorry.  You gave me an option to make a clang-libc++ binary that isn't using C++11 ( Darwin-clang-libc++98 ).  I want to be able to make a clang-libc++ binary that IS using C++11, but I want to do that through cmake ( I'm familiar with it ).

Somewhere in the cmake file just need to add, but you probably don't want to do that all the time.
``` cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -stdlib=libc++ -std=c++1y") # -std=c++1y probably isn't mandatory
```
I can easily add it to the cmake file, I just don't really know how you would like your users to interact with it.  Is adding it as a cmake option the best route?

**Comment by aleks-f** [comment]
I'll have to leave that to @bachp , I have no CMake experience.

**Comment by bachp** [comment]
I'm not sure what's the expectation is. Should Poco automatically build using c++ 11 if the compiler is capable? Or should the user decide?

@aaboyd : Could you try to use `set(CMAKE_CXX_STANDARD 11)` or `set(CMAKE_CXX_STANDARD 14)` instead of the above flags? Documentation [here](http://www.cmake.org/cmake/help/git-master/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD) for more infos.

@aaboyd : BTW: If you don't want to add the above line you could just put it into a local file and e.g. `myenv.cmake` and then call CMake with this files as initial cache `cmake -C myenv.cmake src/`. This is the recommended way to handle non default settings in cmake.

**Comment by aaboyd** [comment]
@bachp thanks for the tip, I tried ```set(CMAKE_CXX_STANDARD 11)``` and ```set(CXX_STANDARD_REQUIRED)``` and it worked for me.  Thanks for that tip.

The ```myenv.cmake``` initial cache would work if it contains the above variables.

I don't know what the expected behavior is.  I didn't think any problems would come up if I just compiled the poco libraries and linked against them.
