### ISSUE TITLE
Logging channel filter by priority

### ISSUE THREAD

**Issue by pwm1234** [pocoproject/poco#858]
This may not be an FAQ, but I have seen others with the same question, and I have seen two different solutions. There is a [stackoverflow question](http://stackoverflow.com/questions/29413883/using-poco-library-how-to-set-different-log-levels-per-channel-in-a-splitter-ch) that Alex answered with "Logging level is per Logger, not per Channel, so you will have to have two loggers ..." 

In addition to this question, I have seen others with different approaches to the same problem (see [PriorityFilter](https://github.com/pocoproject/sandbox/tree/master/Logging) in the Poco sandbox repo and [FilterChannel](https://github.com/mantidproject/mantid/tree/master/Code/Mantid/Framework/Kernel) from the mantidproject. 

Would you consider including a "filter by priority channel" capability in a release of Poco? I believe this capability is essential for a logging framework. I will be glad to work on a fork and provide a pull request, but I did not want to bother if you have a reason for excluding this capability from the Poco Logging subsystem. (Is a github issue like this one the best place to have this discussion or should I have used the forum?)

Thanks,
Phil

**Comment by aleks-f** [comment]
We do not have the reason for excluding it; in fact, the [Logging](https://github.com/pocoproject/sandbox/tree/master/Logging) in sandbox was meant to be added to the releases and separated into  Poco::Log (or Logging, whatever, I'd personally prefer the short name but @obiltschnig may disagree) library but the idea never lived due to the shortage of manpower to realize it. If you want to work on it, go ahead and check occasionally with us to make sure we're ok with the direction you're taking it.

**Comment by Mazyod** [comment]
This is really great, and I would personally like to take a :hocho: at it as well, especially since I need to implement a SlackChannel to deliver errors to Slack.

**Comment by aleks-f** [comment]
Go for it. Make sure to read the [contribution guidelines](https://github.com/pocoproject/poco/blob/develop/CONTRIBUTING.md) first.
