### ISSUE TITLE
Error: The ordinal 342 could not be located in the dynamic link library PocoNetSSLd.dll

### ISSUE THREAD

**Issue by setzer17** [pocoproject/poco#864]
Hello,
I am a beginner trying to learn C++. I downloaded the full Poco version 1.6.0 which contains NetSSL_OpenSSL and Crypto...
I built the libraries using Visual Studio 2013 on Win 8.1 - The build was successful. Now I am trying to run this code:
```cpp
#include <iostream>
#include <Poco/Net/MessageHeader.h>
#include <Poco/Net/MailMessage.h>
#include <Poco/Net/MailRecipient.h>
#include <Poco/Net/NetException.h>
#include <Poco/Net/POP3ClientSession.h>
#include <Poco/Net/SecureStreamSocket.h>
#include <Poco/Net/Context.h>
#include <Poco/AutoPtr.h>
#include <Poco/Net/SSLManager.h>
#include <Poco/Net/ConsoleCertificateHandler.h>
#include <Poco/Net/AcceptCertificateHandler.h>
using namespace std;
using namespace Poco::Net;
using namespace Poco;
int main()
{
	string host = "pop.gmail.com";
	int port = 995;
	string user = "xxx@gmail.com";
	string pass = "xxx";
	try {
		initializeSSL();
		// always accept even if error occurred
		SharedPtr<InvalidCertificateHandler> ptrHandler = new AcceptCertificateHandler(false);
		Context::Ptr ptrContext = new Context(Context::CLIENT_USE, "", "", "", Context::VERIFY_RELAXED, 9, true, "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH");
		SSLManager::instance().initializeClient(0, ptrHandler, ptrContext);
		SocketAddress socketAddress(host, port);
		SecureStreamSocket socket(socketAddress, ptrContext);
		POP3ClientSession session(socket);
		// login
		session.login(user, pass);
		POP3ClientSession::MessageInfoVec messages;
		// list all the messages
		session.listMessages(messages);
		for (auto i = messages.begin(); i != messages.end(); ++i) {
			MessageHeader header;
			session.retrieveHeader((*i).id, header);
			cout << "ID: " << (*i).id << ", "
				<< "Size: " << (*i).size << " bytes" << endl
				<< "From: " << header.get("From") << endl
				<< "Subject: " << header.get("Subject") << endl
				<< "Date: " << header.get("Date") << endl << endl;
		}
		session.close();
		uninitializeSSL();
	}
	catch (POP3Exception &e) {
		cerr << e.displayText() << endl;
		uninitializeSSL();
	}
	catch (NetException &e) {
		cerr << e.displayText() << endl;
		uninitializeSSL();
	}
	return 0;
}
```

I compiled it successfully, but when I run it I get this error:
The ordinal 342 could not be located in the dynamic link library PocoNetSSLd.dll

What's the problem?
Thanks.

**Comment by aleks-f** [comment]
Strange error but I vaguely recall encountering int on Windows 8.1 some time ago.

Best route is to use [Dependency Walker](http://www.dependencywalker.com/) to find out what DLL exactly is being loaded (any old stale binaries on the system) and/or which exported function is missing.

**Comment by calkinsc** [comment]
I had a related error, although ordinal 341 for me from PocoNetSSL (POCO 1.6.1), built for x64 under Windows 10.   Running Dependency Walker showed that the libeay32.dll and ssleay32.dll OpenSSL DLLs were being referenced from the "c:\program files (x86)\intel\icls client\" directory which was in my path, instead of the expected 64-bit DLLs from the version of OpenSSL that I built POCO against.  Copying all of the OpenSSL DLLs from the OpenSSL-Win64 directory (from the Shining Light distribution) into my application directory so they were found before the ones that were in my path fixed the problem.   Now that it was using the right DLLs, the exported function at ordinal 341 that it was looking for was correctly found.  Hope my experience helps!
