### ISSUE TITLE
How to use local timestamp in logging

### ISSUE THREAD

**Issue by DBarzo** [pocoproject/poco#871]
Hi,

is there a way to 'tell' to the Logger which Timestamp to use when it has to create a Message?
I mean something like the Message::setTime() method, but for the Logger object.

Daniele.

**Comment by aleks-f** [comment]
Yes, use [PatternFormatter](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/PatternFormatter.h#L106):
```
PatternFormatter* pPF = new PatternFormatter("%H:%M:%S");
pPF->setTimes("local");
FormattingChannel* pFCConsole = new FormattingChannel(pPF);
pFCConsole->setChannel(new ConsoleChannel);
pFCConsole->open();

Logger& consoleLogger = Logger::create("ConsoleLogger", pFCConsole, Message::PRIO_INFORMATION);
consoleLogger.error("An error message");
```
Alternatively, instead of calling setTimes("local") property, you can use [%L](https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/PatternFormatter.h#L75)

**Comment by DBarzo** [comment]
Thanks a lot Alex!
