### ISSUE TITLE
DatagramSocket is ipv4 by default

### ISSUE THREAD

**Issue by omry** [pocoproject/poco#892]
DatagramSocket constructed with the default constructor is IPV4 by default.
when bind(sa) is called on such a socket, even if the socket address is IPV6, the socket fails to bind.

a stupid workaround is to close() the socket before binding, but a better solution is to properly handle this by switching the underlying socket type to ipv6.

**Comment by obiltschnig** [comment]
Create a new DatagramSocket with the correct SocketAddress and assign it to the default-constructed socket.

**Comment by omry** [comment]
The fact the there is a bind API means it's legitimate to create an unbound socket and bind it later.

**Comment by obiltschnig** [comment]
Changing the behavior of the default constructor would break existing code. An alternative would be providing an additional constructor.

**Comment by omry** [comment]
Thanks for looking into it.

What about my initial suggestion?
Initially a socket can bound to ipv4 by default.
of someone later tries to bind to an ipv6 address, you can replace the underlying socket with an ipv6 implementation.

**Comment by obiltschnig** [comment]
That would mean changing the semantics of bind() to close an existing socket and create a new one. I thought about creating a rebind() method which does that, but see no point as you can simply create a new correctly bound DatagramSocket and assign it to the other one.

The problem here really is the DatagramSocket default constructor, which automatically creates an IPv4 socket. This is different to the other socket default constructors, which create uninitialized sockets and thus don't have this issue.

**Comment by omry** [comment]
Looking forward, IPV6 will become the standard.
Where I work we already use IPV6 internally by default, and new machines don't even have an ipv4 address.
The comment you removed is incorrect, although that would probably be a better behavior on ipv6 only systems.
-		/// Creates a DatagramSocketImpl.
 -		///
 -		/// If the system supports IPv6, the socket will
 -		/// be an IPv6 socket. Otherwise, it will be
 -		/// an IPv4 socket.

Eventually the semantics of this constructor will have to change, either to make ipv6 the default or dynamically decide what kind of underlying socket to create based on the system support.

An alternative is to change the default constructor to not create a socket, and lazily create a socket on the first bind based on the address type.

**Comment by obiltschnig** [comment]
Given there are other constructors for DatagramSocket, I don't see this issue as pressing right now. And it will still be a couple of years until IPv6 is widespread.

**Comment by omry** [comment]
Your patch will alleviate the pressure because it now does allow a creation of an unbound socket.
 
This is not pressing, I already have a workaround as I mentioned.
In general, I think fixing it is the right move though. it's not a critical bug for sure but I did spend a bunch of time debugging around the current issue and I am sure others will get bitten by it when they post to ipv6 only systems.

**Comment by obiltschnig** [comment]
We'll have a chance to fix the default ctor behavior in the upcoming 2.0 release.

**Comment by omry** [comment]
Awesome, I appreciate the effort.

**Comment by obiltschnig** [comment]
fixed in e4fbbe69ba13da0e4ff8aa7ca5ea5192c587f70c

**Comment by omry** [comment]
Thanks!

**Comment by obiltschnig** [comment]
I'll have to remove this fix from the upcoming 1.7.0 release. Since I'll have to keep that release a low-risk upgrade for 1.6.1 users, I'll postpone some changes, including the originally planned UNIX Domain Sockets support in Net library. Instead there will be an 1.8.0 release in early April containing UNIX Domain Sockets support, as well as the changed DatagramSocket/MulticastSocket default constructor (and also PostgreSQL support in Data).

(I'll also remove the additional Unbound constructor fix, as it does not make sense to add this for just one release, then mark it as deprecated). 1.8.0 release branch will be created this week.

**Comment by omry** [comment]
sounds good.
I will reopen it just so it won't skip through the cracks.
