### ISSUE TITLE
Property "transactionMode" of Poco::Data::Session no longer supported in Poco 1.6.0

### ISSUE THREAD

**Issue by danatata** [pocoproject/poco#913]
When I tried to set "transactionMode" property of  a Poco::Data::Session object to "IMMEDIATE" in Poco 1.6, I got a run time error "feature or property not supported".
The same code works in Poco 1.4.6.

From the release note, the support for "transactionMode" property is added in Poco 1.3.4. 
I did not find any other information there indicating it is no longer supported in Poco 1.6.
Is this a bug?

**Comment by aleks-f** [comment]
It's been a long time since 1.4 - things have changed, especially in Data library. See [Data::AbstractsessionImpl](https://github.com/pocoproject/poco/blob/develop/Data/include/Poco/Data/AbstractSessionImpl.h#L55) documentation for features/properties supported for al back-ends. Every back end can add it's own features and properties, see [ODBC](https://github.com/pocoproject/poco/blob/develop/Data/ODBC/src/SessionImpl.cpp#L143) for example.

**Comment by mellery451** [comment]
@aleks-f  -- just want to make sure I understand the response. I think you are confirming that there is indeed no way to obtain "BEGIN IMMEDIATE" transactions with the latest versions of poco (>1.4), but there is conceivably a way to add this to the Session Impl using Features or Properties - correct?

**Comment by aleks-f** [comment]
AFAICT, ```BEGIN IMMEDIATE``` is SQLite specific, so it would require adding some features specific for that back-end (if there are APIs to set it session-wide - I didn't check). Currently, transactions are supported through [Transaction](https://github.com/pocoproject/poco/blob/develop/Data/include/Poco/Data/Transaction.h#L33) and SQLite autoCommit is [not implemented](https://github.com/pocoproject/poco/blob/develop/Data/SQLite/src/SessionImpl.cpp#L247). If you need changes, send a pull request and we will look into it. Keep in mind that will likely not be inclined propagate back-end specifics to the front-end Poco::Data interface because it would break the abstraction. @intensifi
