### ISSUE TITLE
Poco::PostgreSQL problem with PostGIS

### ISSUE THREAD

**Issue by astlin** [pocoproject/poco#949]
I'm using PostGIS extension to manage geospatial data and encounted problem calling PostGIS functions:

string sql = "SELECT ST_AsGeoJson(geom) FROM objects";
Poco::Data::RecordSet rs(*(_pSession), sql);

Throws exception "Data type not supported." 

geom field is of text type so do ST_AsGeoJson returns. any help?

**Comment by intensifi** [comment]
Which C++ or Poco datatype are you trying to return it into?  

PostgreSQL "text" type has to go into a Poco::Data::CLOB.

From PostgreSQLTypes.h
const Oid TEXTOID			= 25;	// CLOB

From Extractor.h
virtual bool extract(std::size_t pos, Poco::Data::CLOB& val);

**Comment by astlin** [comment]
Exception is thrown on RecordSet construction with sql statement before any data return.

**Comment by intensifi** [comment]
Does the string "[PostgreSQL]:" show up in the exception text?   I'm trying to determine if your exception is being caused at the PostgreSQL level or in the main Data classes

**Comment by astlin** [comment]
string sql = "SELECT ST_AsGeoJson(geom) FROM objects"; // this sql works fine in pgsql and other postgresql admin tools

try {
RecordSet rs(*(_pSession), sql);
cout << "Got some data" << endl; // but i never get here
.....
} catch (Exception& de) {
 cout << de.message() << endl;
}

i get "Data exception: Data type not supported." message.

**Comment by intensifi** [comment]
I'll run this through the debugger tonight.

A few questions:

What OS? version?
Which PostgreSQL version?
Which PostGIS version?
Are you using the native driver or ODBC?
Have you tried not using a Poco::Data::RecordSet and received the same result?

**Comment by astlin** [comment]
Development desktop: Ubuntu 15.04, PostgreSQL 9.4, PostGIS 2.1.5
Testing server: Ubuntu 14.10, PostgreSQL 9.3, PostGIS 2.1.
I'm using native driver. Same result on both machines (both are x64). No, i didn't try any other methods i.e tuples yet.

**Comment by intensifi** [comment]
Progress report:

On
Postgres 9.4
PostGIS 2.1.7
MacOSX 10.10.5

With 
create table public.objects 
(
  geom geometry
)

The following code DOES NOT throw an exception:

    Poco::Data::CLOB clob;
    
    try { *_pSession << "SELECT ST_AsGeoJson(geom) FROM objects", into(clob), now;  }
    catch(Poco::Exception& ex){ std::cout << ex.what() << std::endl; fail (funct); }

nor does

    std::vector< Poco::Data::CLOB > clobVector;
    
    try { *_pSession << "SELECT ST_AsGeoJson(geom) FROM objects", into(clobVector), now;  }
    catch(Poco::Exception& ex){ std::cout << ex.what() << std::endl; fail (funct); }

However if the into(clob) or into(clobVector) arguments are removed an "Invalid Argument" exception is thrown.

Your code also throws an invalid argument exception:

    std::string sql = "SELECT ST_AsGeoJson(geom) FROM objects";
    try { Poco::Data::RecordSet rs(*(_pSession), sql); }
    catch(StatementException& se){ std::cout << se.displayText() << std::endl; fail (funct); }
    catch(Poco::Exception& ex){ std::cout << ex.what() << std::endl; fail (funct); }

Tracking this down the problem is coming from the Poco::Data::Statement constructor in both cases where an exception is being thrown.

**Comment by intensifi** [comment]
in the interim try the following statement on your end:

SELECT CAST( ST_AsGeoJson(geom) AS VARCHAR) FROM objects

I am creating a test where I create a table with all the valid postgresql data types and and verify that the PostgreSQL adapter can do a select * from it and not have an invalid data type exception.  More tomorrow.  Out of time tonight.

**Comment by astlin** [comment]
Thanks a lot. CAST AS VARCHAR worked for me.

**Comment by intensifi** [comment]
Problem isolated:

A column of data type "text" causes the exception.  It's is supposed to be recognized as TEXTOID, but for some reason that is not the case.  I will try to fix tomorrow.

Your bug has highlighted a missing test case.  That being create a table of all the valid database data types that are supposed to have a mapping to Poco::Data types and perform a "select *" to verify the mappings are working.

**Comment by intensifi** [comment]
CAST AS VARCHAR is temporary.  If you end up with a result that does not fit in a varchar you will run into an error or truncation.

**Comment by astlin** [comment]
Sorry for being impatient. Is there any progress with fix?

**Comment by intensifi** [comment]
Progress yes.  fix no.  Currently it's a head scratcher.

I hope to get back to it tonight after I finish coding some updates for my day job.

**Comment by intensifi** [comment]
I haven't forgotten about you.  I'm still working on this.

**Comment by intensifi** [comment]
Ok,  I just found the problem and created a pull request for the fix.
The issue was not in the PostgreSQL adapter at all.  The issue was in:

Data/src/StatementImpl.cpp

There is s switch statement towards the bottom dedicated to making extractors for RecordSets.  It was missing a case statement for Poco::Data::CLOBs.

If you can't wait for the Pull Request to finish, find the switch statement and copy the two lines dedicated to BLOB.  Then paste right below and change BLOB to CLOB on the two lines you pasted in.

Again my apologies for this taking so long.  I have been very busy as of late.

**Comment by astlin** [comment]
Thank you. Now it works like a charm.
